### ISSUE TITLE
Pip install fails on OS-X 

### ISSUE THREAD

**Issue by alapite** [openai/baselines#1]
On macOS Sierra (10.12.5) attempting to run `pip install baselines` results in the following error message: 
```Collecting baselines
  Using cached baselines-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/nq/0xqx24zn7dn5qmzxkl4dyp9r0000gn/T/pip-build-nBjPkA/baselines/setup.py", line 8, in <module>
        with open(os.path.join(repo_dir, "README.md")) as f:
    IOError: [Errno 2] No such file or directory: '/private/var/folders/nq/0xqx24zn7dn5qmzxkl4dyp9r0000gn/T/pip-build-nBjPkA/baselines/README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/nq/0xqx24zn7dn5qmzxkl4dyp9r0000gn/T/pip-build-nBjPkA/baselines/```

**Comment by siemanko** [comment]
@alapite thanks for reporting this! Should be fixed now.

**Comment by siemanko** [comment]
Closing the issue, please comment if the issie persists.

**Comment by varpandit** [comment]
I am facing the similar issue. Kindly provide the solution.

**Comment by tennenboke** [comment]
I also have the same issue.Please provide a solution
