### ISSUE TITLE
Non-compatibility with mujoco-py 2.0?

### ISSUE THREAD

**Issue by kracon7** [openai/baselines#1055]
I installed mujoco-py 2.0 which seems to be incompatible with baselines.
I'm using ubuntu 16.04 and python3.5
This is wierd because I had another laptop with the same configurations, and I had no issue installing baselines.
Any help would be appreciated. Thanks!

```sh
(pytorch_mujoco) jc@jc-XPS-8930:~$ pip install baselines
Requirement already satisfied: baselines in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (0.1.5)
Requirement already satisfied: tqdm in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from baselines) (4.40.2)
Requirement already satisfied: progressbar2 in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from baselines) (3.47.0)
Requirement already satisfied: tensorflow>=1.4.0 in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from baselines) (2.0.0)
Requirement already satisfied: mpi4py in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from baselines) (3.0.3)
Requirement already satisfied: joblib in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from baselines) (0.13.2)
Requirement already satisfied: cloudpickle in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from baselines) (1.2.2)
Requirement already satisfied: gym[atari,classic_control,mujoco,robotics] in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from baselines) (0.15.4)
Requirement already satisfied: zmq in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from baselines) (0.0.0)
Requirement already satisfied: scipy in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from baselines) (1.1.0)
Requirement already satisfied: dill in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from baselines) (0.3.1.1)
Requirement already satisfied: click in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from baselines) (7.0)
Requirement already satisfied: python-utils>=2.3.0 in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from progressbar2->baselines) (2.3.0)
Requirement already satisfied: six in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from progressbar2->baselines) (1.12.0)
Requirement already satisfied: protobuf>=3.6.1 in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from tensorflow>=1.4.0->baselines) (3.11.1)
Requirement already satisfied: google-pasta>=0.1.6 in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from tensorflow>=1.4.0->baselines) (0.1.8)
Requirement already satisfied: keras-applications>=1.0.8 in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from tensorflow>=1.4.0->baselines) (1.0.8)
Requirement already satisfied: wheel>=0.26 in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from tensorflow>=1.4.0->baselines) (0.33.6)
Requirement already satisfied: absl-py>=0.7.0 in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from tensorflow>=1.4.0->baselines) (0.8.1)
Requirement already satisfied: astor>=0.6.0 in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from tensorflow>=1.4.0->baselines) (0.8.1)
Requirement already satisfied: keras-preprocessing>=1.0.5 in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from tensorflow>=1.4.0->baselines) (1.1.0)
Requirement already satisfied: tensorflow-estimator<2.1.0,>=2.0.0 in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from tensorflow>=1.4.0->baselines) (2.0.1)
Requirement already satisfied: termcolor>=1.1.0 in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from tensorflow>=1.4.0->baselines) (1.1.0)
Requirement already satisfied: wrapt>=1.11.1 in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from tensorflow>=1.4.0->baselines) (1.11.2)
Requirement already satisfied: grpcio>=1.8.6 in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from tensorflow>=1.4.0->baselines) (1.25.0)
Requirement already satisfied: gast==0.2.2 in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from tensorflow>=1.4.0->baselines) (0.2.2)
Requirement already satisfied: opt-einsum>=2.3.2 in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from tensorflow>=1.4.0->baselines) (3.1.0)
Requirement already satisfied: numpy<2.0,>=1.16.0 in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from tensorflow>=1.4.0->baselines) (1.17.0)
Requirement already satisfied: tensorboard<2.1.0,>=2.0.0 in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from tensorflow>=1.4.0->baselines) (2.0.2)
Requirement already satisfied: opencv-python in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from gym[atari,classic_control,mujoco,robotics]->baselines) (4.1.2.30)
Requirement already satisfied: pyglet<=1.3.2,>=1.2.0 in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from gym[atari,classic_control,mujoco,robotics]->baselines) (1.3.2)
Requirement already satisfied: Pillow; extra == "atari" in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from gym[atari,classic_control,mujoco,robotics]->baselines) (6.1.0)
Requirement already satisfied: atari-py~=0.2.0; extra == "atari" in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from gym[atari,classic_control,mujoco,robotics]->baselines) (0.2.6)
Requirement already satisfied: imageio; extra == "mujoco" in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from gym[atari,classic_control,mujoco,robotics]->baselines) (2.5.0)
Collecting mujoco-py<2.0,>=1.50; extra == "mujoco"
  Using cached https://files.pythonhosted.org/packages/cf/8c/64e0630b3d450244feef0688d90eab2448631e40ba6bdbd90a70b84898e7/mujoco-py-1.50.1.68.tar.gz
Requirement already satisfied: pyzmq in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from zmq->baselines) (18.1.0)
Requirement already satisfied: setuptools in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from protobuf>=3.6.1->tensorflow>=1.4.0->baselines) (41.2.0)
Requirement already satisfied: h5py in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from keras-applications>=1.0.8->tensorflow>=1.4.0->baselines) (2.10.0)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from tensorboard<2.1.0,>=2.0.0->tensorflow>=1.4.0->baselines) (0.4.1)
Requirement already satisfied: markdown>=2.6.8 in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from tensorboard<2.1.0,>=2.0.0->tensorflow>=1.4.0->baselines) (3.1.1)
Requirement already satisfied: werkzeug>=0.11.15 in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from tensorboard<2.1.0,>=2.0.0->tensorflow>=1.4.0->baselines) (0.16.0)
Requirement already satisfied: google-auth<2,>=1.6.3 in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from tensorboard<2.1.0,>=2.0.0->tensorflow>=1.4.0->baselines) (1.8.2)
Requirement already satisfied: requests<3,>=2.21.0 in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from tensorboard<2.1.0,>=2.0.0->tensorflow>=1.4.0->baselines) (2.22.0)
Requirement already satisfied: future in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from pyglet<=1.3.2,>=1.2.0->gym[atari,classic_control,mujoco,robotics]->baselines) (0.18.2)
Requirement already satisfied: glfw>=1.4.0 in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from mujoco-py<2.0,>=1.50; extra == "mujoco"->gym[atari,classic_control,mujoco,robotics]->baselines) (1.8.2)
Requirement already satisfied: Cython>=0.27.2 in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from mujoco-py<2.0,>=1.50; extra == "mujoco"->gym[atari,classic_control,mujoco,robotics]->baselines) (0.29.13)
Requirement already satisfied: cffi>=1.10 in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from mujoco-py<2.0,>=1.50; extra == "mujoco"->gym[atari,classic_control,mujoco,robotics]->baselines) (1.12.3)
Requirement already satisfied: lockfile>=0.12.2 in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from mujoco-py<2.0,>=1.50; extra == "mujoco"->gym[atari,classic_control,mujoco,robotics]->baselines) (0.12.2)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.1.0,>=2.0.0->tensorflow>=1.4.0->baselines) (1.3.0)
Requirement already satisfied: rsa<4.1,>=3.1.4 in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from google-auth<2,>=1.6.3->tensorboard<2.1.0,>=2.0.0->tensorflow>=1.4.0->baselines) (4.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from google-auth<2,>=1.6.3->tensorboard<2.1.0,>=2.0.0->tensorflow>=1.4.0->baselines) (0.2.7)
Requirement already satisfied: cachetools<3.2,>=2.0.0 in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from google-auth<2,>=1.6.3->tensorboard<2.1.0,>=2.0.0->tensorflow>=1.4.0->baselines) (3.1.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from requests<3,>=2.21.0->tensorboard<2.1.0,>=2.0.0->tensorflow>=1.4.0->baselines) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from requests<3,>=2.21.0->tensorboard<2.1.0,>=2.0.0->tensorflow>=1.4.0->baselines) (1.25.7)
Requirement already satisfied: idna<2.9,>=2.5 in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from requests<3,>=2.21.0->tensorboard<2.1.0,>=2.0.0->tensorflow>=1.4.0->baselines) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from requests<3,>=2.21.0->tensorboard<2.1.0,>=2.0.0->tensorflow>=1.4.0->baselines) (2019.11.28)
Requirement already satisfied: pycparser in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from cffi>=1.10->mujoco-py<2.0,>=1.50; extra == "mujoco"->gym[atari,classic_control,mujoco,robotics]->baselines) (2.19)
Requirement already satisfied: oauthlib>=3.0.0 in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.1.0,>=2.0.0->tensorflow>=1.4.0->baselines) (3.1.0)
Requirement already satisfied: pyasn1>=0.1.3 in /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages (from rsa<4.1,>=3.1.4->google-auth<2,>=1.6.3->tensorboard<2.1.0,>=2.0.0->tensorflow>=1.4.0->baselines) (0.4.8)
Building wheels for collected packages: mujoco-py
  Building wheel for mujoco-py (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/jc/Envs/pytorch_mujoco/bin/python3.5 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w5ll41q0/mujoco-py/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w5ll41q0/mujoco-py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-7hl90ic7 --python-tag cp35
       cwd: /tmp/pip-install-w5ll41q0/mujoco-py/
  Complete output (54 lines):
  running bdist_wheel
  running build
  
  You appear to be missing MuJoCo.  We expected to find the file here: /home/jc/.mujoco/mjpro150
  
  This package only provides python bindings, the library must be installed separately.
  
  Please follow the instructions on the README to install MuJoCo
  
      https://github.com/openai/mujoco-py#install-mujoco
  
  Which can be downloaded from the website
  
      https://www.roboti.us/index.html
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-w5ll41q0/mujoco-py/setup.py", line 44, in <module>
      tests_require=read_requirements_file('requirements.dev.txt'),
    File "/home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-w5ll41q0/mujoco-py/setup.py", line 28, in run
      import mujoco_py  # noqa: force build
    File "/tmp/pip-install-w5ll41q0/mujoco-py/mujoco_py/__init__.py", line 3, in <module>
      from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
    File "/tmp/pip-install-w5ll41q0/mujoco-py/mujoco_py/builder.py", line 502, in <module>
      mjpro_path, key_path = discover_mujoco()
    File "/tmp/pip-install-w5ll41q0/mujoco-py/mujoco_py/utils.py", line 93, in discover_mujoco
      raise Exception(message)
  Exception:
  You appear to be missing MuJoCo.  We expected to find the file here: /home/jc/.mujoco/mjpro150
  
  This package only provides python bindings, the library must be installed separately.
  
  Please follow the instructions on the README to install MuJoCo
  
      https://github.com/openai/mujoco-py#install-mujoco
  
  Which can be downloaded from the website
  
      https://www.roboti.us/index.html
  
  ----------------------------------------
  ERROR: Failed building wheel for mujoco-py
  Running setup.py clean for mujoco-py
Failed to build mujoco-py
Installing collected packages: mujoco-py
  Found existing installation: mujoco-py 2.0.2.5
    Uninstalling mujoco-py-2.0.2.5:
      Successfully uninstalled mujoco-py-2.0.2.5
    Running setup.py install for mujoco-py ... error
    ERROR: Command errored out with exit status 1:
     command: /home/jc/Envs/pytorch_mujoco/bin/python3.5 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w5ll41q0/mujoco-py/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w5ll41q0/mujoco-py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-2qkyqdo2/install-record.txt --single-version-externally-managed --compile --install-headers /home/jc/Envs/pytorch_mujoco/include/site/python3.5/mujoco-py
         cwd: /tmp/pip-install-w5ll41q0/mujoco-py/
    Complete output (56 lines):
    running install
    running build
    
    You appear to be missing MuJoCo.  We expected to find the file here: /home/jc/.mujoco/mjpro150
    
    This package only provides python bindings, the library must be installed separately.
    
    Please follow the instructions on the README to install MuJoCo
    
        https://github.com/openai/mujoco-py#install-mujoco
    
    Which can be downloaded from the website
    
        https://www.roboti.us/index.html
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-w5ll41q0/mujoco-py/setup.py", line 44, in <module>
        tests_require=read_requirements_file('requirements.dev.txt'),
      File "/home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.5/distutils/command/install.py", line 583, in run
        self.run_command('build')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-w5ll41q0/mujoco-py/setup.py", line 28, in run
        import mujoco_py  # noqa: force build
      File "/tmp/pip-install-w5ll41q0/mujoco-py/mujoco_py/__init__.py", line 3, in <module>
        from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
      File "/tmp/pip-install-w5ll41q0/mujoco-py/mujoco_py/builder.py", line 502, in <module>
        mjpro_path, key_path = discover_mujoco()
      File "/tmp/pip-install-w5ll41q0/mujoco-py/mujoco_py/utils.py", line 93, in discover_mujoco
        raise Exception(message)
    Exception:
    You appear to be missing MuJoCo.  We expected to find the file here: /home/jc/.mujoco/mjpro150
    
    This package only provides python bindings, the library must be installed separately.
    
    Please follow the instructions on the README to install MuJoCo
    
        https://github.com/openai/mujoco-py#install-mujoco
    
    Which can be downloaded from the website
    
        https://www.roboti.us/index.html
    
    ----------------------------------------
  Rolling back uninstall of mujoco-py
  Moving to /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages/mujoco_py-2.0.2.5.dist-info/
   from /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages/~ujoco_py-2.0.2.5.dist-info
  Moving to /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages/mujoco_py/
   from /home/jc/Envs/pytorch_mujoco/lib/python3.5/site-packages/~ujoco_py
ERROR: Command errored out with exit status 1: /home/jc/Envs/pytorch_mujoco/bin/python3.5 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w5ll41q0/mujoco-py/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w5ll41q0/mujoco-py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-2qkyqdo2/install-record.txt --single-version-externally-managed --compile --install-headers /home/jc/Envs/pytorch_mujoco/include/site/python3.5/mujoco-py Check the logs for full command output.
(pytorch_mujoco) jc@jc-XPS-8930:~$ pip freeze |grep mujoco
mujoco-py==2.0.2.5
```

**Comment by joehays** [comment]
Take a look at: https://github.com/openai/gym/issues/1883
