### ISSUE TITLE
'install_requires' problem when installing using pip

### ISSUE THREAD

**Issue by cypreess** [openai/baselines#111]
Hi,

I am trying to install baselines from directory (master):

```
$ pip install -e baselines/
Obtaining file:///Users/cypreess/dev/baselines
    Complete output from command python setup.py egg_info:
    error in baselines setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected ',' or end-of-list in gym>=0.9.1[all] at [all]

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /Users/cypreess/dev/baselines/
```

Looks like there is some problem with `[all]` specifier.

```
$ python --version
Python 3.6.0
$ pip --version
pip 9.0.1 from /Users/cypreess/.virtualenvs/t/lib/python3.6/site-packages (python 3.6)
```

I am using Mac OS 10.11.

**Comment by joschu** [comment]
Thanks, fixed

**Comment by kxhit** [comment]
Hi, I meet a similar problem.

`$ pip install baselines

 Collecting baselines
  Using cached baselines-0.1.5.tar.gz
Collecting gym[atari,classic_control,mujoco,robotics] (from baselines)
  Using cached gym-0.10.4.tar.gz
Requirement already satisfied: scipy in /usr/local/lib/python3.5/dist-packages (from baselines)
Requirement already satisfied: tqdm in /usr/local/lib/python3.5/dist-packages (from baselines)
Collecting joblib (from baselines)
  Using cached joblib-0.11-py2.py3-none-any.whl
Collecting zmq (from baselines)
  Using cached zmq-0.0.0.tar.gz
Collecting dill (from baselines)
  Using cached dill-0.2.7.1.tar.gz
Collecting progressbar2 (from baselines)
  Using cached progressbar2-3.36.0-py2.py3-none-any.whl
Collecting mpi4py (from baselines)
  Using cached mpi4py-3.0.0.tar.gz
Collecting cloudpickle (from baselines)
  Using cached cloudpickle-0.5.2-py2.py3-none-any.whl
Requirement already satisfied: tensorflow>=1.4.0 in /usr/local/lib/python3.5/dist-packages (from baselines)
Collecting click (from baselines)
  Using cached click-6.7-py2.py3-none-any.whl
Requirement already satisfied: numpy>=1.10.4 in /usr/local/lib/python3.5/dist-packages (from gym[atari,classic_control,mujoco,robotics]->baselines)
Requirement already satisfied: requests>=2.0 in /usr/lib/python3/dist-packages (from gym[atari,classic_control,mujoco,robotics]->baselines)
Requirement already satisfied: six in /usr/local/lib/python3.5/dist-packages (from gym[atari,classic_control,mujoco,robotics]->baselines)
Requirement already satisfied: pyglet>=1.2.0 in /usr/local/lib/python3.5/dist-packages (from gym[atari,classic_control,mujoco,robotics]->baselines)
Collecting atari_py>=0.1.1 (from gym[atari,classic_control,mujoco,robotics]->baselines)
  Using cached atari-py-0.1.1.tar.gz
Requirement already satisfied: Pillow in /usr/local/lib/python3.5/dist-packages (from gym[atari,classic_control,mujoco,robotics]->baselines)
Collecting PyOpenGL (from gym[atari,classic_control,mujoco,robotics]->baselines)
  Using cached PyOpenGL-3.1.0.tar.gz
Collecting mujoco_py>=1.50 (from gym[atari,classic_control,mujoco,robotics]->baselines)
  Using cached mujoco-py-1.50.1.42.tar.gz
    Complete output from command python setup.py egg_info:
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
     #include <ffi.h>
                     ^
    compilation terminated.
    Traceback (most recent call last):
      File "/usr/lib/python3.5/distutils/unixccompiler.py", line 118, in _compile
        extra_postargs)
      File "/usr/lib/python3.5/distutils/ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/usr/lib/python3.5/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/usr/lib/python3.5/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.5/dist-packages/setuptools/command/bdist_egg.py", line 170, in run
        cmd = self.call_command('install_lib', warn_dir=0)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/command/bdist_egg.py", line 156, in call_command
        self.run_command(cmdname)
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.5/dist-packages/setuptools/command/install_lib.py", line 11, in run
        self.build()
      File "/usr/lib/python3.5/distutils/command/install_lib.py", line 109, in build
        self.run_command('build_ext')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.5/dist-packages/setuptools/command/build_ext.py", line 75, in run
        _build_ext.run(self)
      File "/usr/local/lib/python3.5/dist-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/usr/local/lib/python3.5/dist-packages/Cython/Distutils/old_build_ext.py", line 194, in build_extensions
        self.build_extension(ext)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/command/build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 533, in build_extension
        depends=ext.depends)
      File "/usr/lib/python3.5/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/usr/lib/python3.5/distutils/unixccompiler.py", line 120, in _compile
        raise CompileError(msg)
    distutils.errors.CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-nuw63vmu/cffi-1.11.5/setup.py", line 240, in <module>
      File "/usr/local/lib/python3.5/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.5/distutils/core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_install.py", line 1104, in run_setup
        run_setup(setup_script, args)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/usr/local/lib/python3.5/dist-packages/pkg_resources/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-nuw63vmu/cffi-1.11.5/setup.py", line 240, in <module>
      File "/usr/local/lib/python3.5/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.5/distutils/core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-tfk3kfji/mujoco-py/setup.py", line 52, in <module>
        cmdclass={'build': Build},
      File "/usr/local/lib/python3.5/dist-packages/setuptools/__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/__init__.py", line 123, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/dist.py", line 453, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 866, in resolve
        replace_conflicting=replace_conflicting
      File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1146, in best_match
        return self.obtain(req, installer)
      File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1158, in obtain
        return installer(requirement)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/dist.py", line 520, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_install.py", line 672, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_install.py", line 698, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_install.py", line 879, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_install.py", line 1118, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_install.py", line 1106, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-tfk3kfji/mujoco-py/
`
`$ python --version
Python 3.5.3
$ pip --version
pip 9.0.3 from /usr/local/lib/python3.5/dist-packages (python 3.5)
`
I am using ubuntu14.04. Any suggestions? Thanks!

**Comment by tennenboke** [comment]
I have the same version and issue,please provide a solution.Thanks!

**Comment by AndyRiedel** [comment]
I fixed a similar issue with the same error message with 
`pip install tensorflow`
