### ISSUE TITLE
AttributeError: 'MultiDiscrete' object has no attribute 'n'

### ISSUE THREAD

**Issue by hridoylego** [openai/baselines#1113]
I follow the instruction here:
https://github.com/Unity-Technologies/ml-agents/tree/master/gym-unity

To train the GridWorld agent of ml-agents using the deepq algorithm using the train_unity.py code and ran into the following error:

```
2020-06-13 15:39:04 INFO [environment.py:111] Connected to Unity environment with package version 1.0.2-preview and communication version 1.0.0
2020-06-13 15:39:05 INFO [environment.py:342] Connected new brain:
GridWorld?team=0
2020-06-13 15:39:05 WARNING [__init__.py:83] `uint8_visual was set to true, but visual observations are not in use. This setting will not have any effect.
Logging to ./logs
WARNING:tensorflow:From c:\users\hridoy\documents\baselines\baselines\common\tf_util.py:53: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

2020-06-13 15:39:05 WARNING [deprecation_wrapper.py:119] From c:\users\hridoy\documents\baselines\baselines\common\tf_util.py:53: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

WARNING:tensorflow:From c:\users\hridoy\documents\baselines\baselines\common\tf_util.py:63: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

2020-06-13 15:39:05 WARNING [deprecation_wrapper.py:119] From c:\users\hridoy\documents\baselines\baselines\common\tf_util.py:63: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From c:\users\hridoy\documents\baselines\baselines\common\tf_util.py:70: The name tf.InteractiveSession is deprecated. Please use tf.compat.v1.InteractiveSession instead.

2020-06-13 15:39:05 WARNING [deprecation_wrapper.py:119] From c:\users\hridoy\documents\baselines\baselines\common\tf_util.py:70: The name tf.InteractiveSession is deprecated. Please use tf.compat.v1.InteractiveSession instead.

WARNING:tensorflow:From c:\users\hridoy\documents\baselines\baselines\common\misc_util.py:58: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.

2020-06-13 15:39:05 WARNING [deprecation_wrapper.py:119] From c:\users\hridoy\documents\baselines\baselines\common\misc_util.py:58: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.

Traceback (most recent call last):
  File "C:\Users\hridoy\Anaconda3\envs\ml-agents\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\hridoy\Anaconda3\envs\ml-agents\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\hridoy\ml-agents\Project\env\train_unity.py", line 35, in <module>
    main()
  File "C:\Users\hridoy\ml-agents\Project\env\train_unity.py", line 29, in main
    dueling=True
  File "c:\users\hridoy\documents\baselines\baselines\deepq\deepq.py", line 204, in learn
    num_actions=env.action_space.n,
AttributeError: 'MultiDiscrete' object has no attribute 'n'
2020-06-13 15:39:06 INFO [environment.py:498] Environment shut down with return code 0 (CTRL_C_EVENT).

```

Here is the unity setup from which I built the environment:

![image](https://user-images.githubusercontent.com/59928531/84073795-78cfcd00-a99f-11ea-9397-9af4205bf208.png)

I had to delete the agent view area or I get the error there is more than 1 agent in the scene.

Here are the files in my env directory:

![image](https://user-images.githubusercontent.com/59928531/84073920-b2a0d380-a99f-11ea-9016-ee7e0d1965bc.png)

- Unity Version: [Unity 2019.3.5f1]
- OS + version: [Windows 10]
-_Baselines version_:0.1.6
- _ML-Agents version_: ML-Agents v0.16.1
- _TensorFlow version_: 1.14.0
- _Environment_: Gridworld

**Comment by hridoylego** [comment]
The flatten_branched flag needed to be set to True so the space type would be Discrete instead of Multidiscrete.

Simply change:
env = UnityToGymWrapper(unity_env, 0, uint8_visual=True)
With:
env = UnityToGymWrapper(unity_env, flatten_branched = True, uint8_visual=True)
