### ISSUE TITLE
ImportError: cannot import name 'FlattenDictWrapper' - tf2 version

### ISSUE THREAD

**Issue by ashutoshtiwari13** [openai/baselines#1129]
Post Installing the tf2 version of baselines , the baselines.run for PPO seems to not work as expected. 
Is this error due to a version mismatch? or a bug ? 
Using , 
TensorFlow : 2.2.0
Gym : 0.15.7
mujoco200 version

>> python -m baselines.run --alg=ppo2 --env=Humanoid-v2 --network=mlp --num_timesteps=2e7
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/leo/Desktop/openai-baseline/baselines/baselines/run.py", line 12, in <module>
    from baselines.common.cmd_util import common_arg_parser, parse_unknown_args, make_vec_env, make_env
  File "/home/leo/Desktop/openai-baseline/baselines/baselines/common/cmd_util.py", line 12, in <module>
    from gym.wrappers import FlattenDictWrapper
ImportError: cannot import name 'FlattenDictWrapper'

I could remove the error with some changes. Can you please confirm if this is a bug ? I can submit a PR for the same.

**Comment by samiulextreem** [comment]
Baseline does not support tf 2 . revert to tf 1.15 .Hope this solve the issue

**Comment by dawierha** [comment]
> 
> 
> Baseline does not support tf 2 . revert to tf 1.15 .Hope this solve the issue

I think he's talking about the tf2 branch of this repo.

As for OP's question, I think you need gym<0.14 installed
