### ISSUE TITLE
Missing parameters on latest baselines

### ISSUE THREAD

**Issue by sarmientoj24** [openai/baselines#1166]
I am currently using baselines==0.1.5

I am getting these missing parameters

**Missing total_timesteps for deepq**
```
>>> act = deepq.learn(env, 'mlp', lr=1e-3, total_timesteps=5000, buffer_size=500, exploration_fraction=0.1, exploration_final_eps=0.02, print_freq=10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: learn() got an unexpected keyword argument 'total_timesteps'
```

**No learn() in ppo2**
```
>>> act = ppo2.learn(network='mlp', env=env, total_timesteps=5000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'baselines.ppo2' has no attribute 'learn'
```

**Comment by sarmientoj24** [comment]
Any update on this?

**Comment by minhlong94** [comment]
Latest baselines is not "latest". This repo is no longer in development. You can use Stable-Baselines3, a better fork version.
