### ISSUE TITLE
Running Baselines on Windows

### ISSUE THREAD

**Issue by donamin** [openai/baselines#135]
Hi

I cloned the repository on Windows (I had to remove Atari dependency from setup file).
Now when I try to run codes (DDPG, PPO), I get the following error:

`Traceback (most recent call last):
  File "main.py", line 10, in <module>
    import baselines.ddpg.training as training
  File "e:\baselines\baselines\ddpg\training.py", line 6, in <
module>
    from baselines.ddpg.ddpg import DDPG
  File "e:\baselines\baselines\ddpg\ddpg.py", line 9, in <modu
le>
    from baselines.common.mpi_adam import MpiAdam
  File "e:\baselines\baselines\common\mpi_adam.py", line 1, in
 <module>
    from mpi4py import MPI
ImportError: DLL load failed: The specified module could not be found.`

Any ideas how to solve this?

**Comment by donamin** [comment]
Never mind this link helped me:
https://bitbucket.org/mpi4py/mpi4py/issues/67/from-mpi4py-import-mpi-dont-work
