### ISSUE TITLE
Which version of python should I be using?

### ISSUE THREAD

**Issue by MogicianWu** [openai/baselines#166]
I currently have a python 3.4 on a Ubuntu with a Intel® Xeon(R) CPU E5-1620 0 @ 3.60GHz CPU and a Titan X graphics card. When I tried to run DDPG example, the following error occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/cheng/Documents/Bruce_Wu/openai_gym/baselines/baselines/ddpg/main.py", line 17, in <module>
    import baselines.ddpg.training as training
  File "/home/cheng/Documents/Bruce_Wu/openai_gym/baselines/baselines/ddpg/training.py", line 6, in <module>
    from baselines.ddpg.ddpg import DDPG
  File "/home/cheng/Documents/Bruce_Wu/openai_gym/baselines/baselines/ddpg/ddpg.py", line 343
    stats = {**stats, **self.param_noise.get_stats()}
              ^
SyntaxError: invalid syntax

**Comment by zhujiapeng** [comment]
I met the same question...

**Comment by unixpickle** [comment]
Try Python 3.5 or newer. In general, this should run if you use conda to keep a clean, up-to-date Python installation.

**Comment by shuangao** [comment]
I am using Python 3.5.2, but still get the same problem.
