### ISSUE TITLE
ModuleNotFoundError: No module named 'baselines.bench.simple_bench'

### ISSUE THREAD

**Issue by abhigenie92** [openai/baselines#197]
```
~/D/p/j/c/l/b/b/ppo1 [master]× » python                                                                (ppo_latest) 19:49:18
Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:14:59)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import baselines
>>> from baselines import bench
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda/envs/ppo_latest/lib/python3.6/site-packages/baselines-0.1.4-py3.6.egg/baselines/bench/__init__.py", line 3, in <module>
ModuleNotFoundError: No module named 'baselines.bench.simple_bench'
>>> exit()

~/D/p/j/c/l/b/b/ppo1 [master]× » conda list                                                            (ppo_latest) 19:49:43
# packages in environment at /anaconda/envs/ppo_latest:
#
atari-py                  0.1.1                     <pip>
azure                     1.0.3                     <pip>
azure-common              1.1.8                     <pip>
azure-mgmt                0.20.2                    <pip>
azure-mgmt-common         0.20.0                    <pip>
azure-mgmt-compute        0.20.1                    <pip>
azure-mgmt-network        0.20.1                    <pip>
azure-mgmt-nspkg          2.0.0                     <pip>
azure-mgmt-resource       0.20.1                    <pip>
azure-mgmt-storage        0.20.0                    <pip>
azure-nspkg               2.0.0                     <pip>
azure-servicebus          0.20.1                    <pip>
azure-servicemanagement-legacy 0.20.2                    <pip>
azure-storage             0.20.3                    <pip>
bleach                    1.5.0                     <pip>
certifi                   2017.11.5                 <pip>
chardet                   3.0.4                     <pip>
dill                      0.2.7.1                   <pip>
enum34                    1.1.6                     <pip>
gym                       0.9.4                     <pip>
html5lib                  0.9999999                 <pip>
idna                      2.6                       <pip>
imageio                   2.2.0                     <pip>
intel-openmp              2018.0.0             h68bdfb3_7    anaconda
joblib                    0.11                      <pip>
libcxx                    4.0.1                h579ed51_0    anaconda
libcxxabi                 4.0.1                hebd6815_0    anaconda
libgfortran               3.0.1                h93005f0_2    anaconda
Markdown                  2.6.9                     <pip>
mkl                       2018.0.0             h5ef208c_6    anaconda
mpi4py                    2.0.0                    py36_0
mujoco-py                 0.5.7                     <pip>
numpy                     1.13.3           py36h2cdce51_0    anaconda
olefile                   0.44                      <pip>
openmpi                   1.6.3                         1
openssl                   1.0.2l                        0
Pillow                    4.3.0                     <pip>
pip                       9.0.1                    py36_1
progressbar2              3.34.3                    <pip>
protobuf                  3.4.0                     <pip>
pyglet                    1.2.4                     <pip>
PyOpenGL                  3.1.0                     <pip>
python                    3.6.2                         0
python-utils              2.2.0                     <pip>
pyzmq                     17.0.0b2                  <pip>
readline                  6.2                           2
requests                  2.18.4                    <pip>
scipy                     0.19.1           py36h3e758e1_3    anaconda
setuptools                27.2.0                   py36_0
six                       1.11.0                    <pip>
sqlite                    3.13.0                        0
tensorflow                1.4.0                     <pip>
tensorflow-tensorboard    0.4.0rc2                  <pip>
tk                        8.5.18                        0
tqdm                      4.19.4                    <pip>
urllib3                   1.22                      <pip>
Werkzeug                  0.12.2                    <pip>
wheel                     0.29.0                   py36_0
xz                        5.2.2                         1
zlib                      1.2.8                         3

~/D/p/j/c/l/b/b/ppo1 [master]× » pip list                                                              (ppo_latest) 19:49:47
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
atari-py (0.1.1)
azure (1.0.3)
azure-common (1.1.8)
azure-mgmt (0.20.2)
azure-mgmt-common (0.20.0)
azure-mgmt-compute (0.20.1)
azure-mgmt-network (0.20.1)
azure-mgmt-nspkg (2.0.0)
azure-mgmt-resource (0.20.1)
azure-mgmt-storage (0.20.0)
azure-nspkg (2.0.0)
azure-servicebus (0.20.1)
azure-servicemanagement-legacy (0.20.2)
azure-storage (0.20.3)
baselines (0.1.4)
bleach (1.5.0)
certifi (2017.11.5)
chardet (3.0.4)
dill (0.2.7.1)
enum34 (1.1.6)
gym (0.9.4)
html5lib (0.9999999)
idna (2.6)
imageio (2.2.0)
joblib (0.11)
Markdown (2.6.9)
mpi4py (2.0.0)
mujoco-py (0.5.7)
numpy (1.13.3)
olefile (0.44)
Pillow (4.3.0)
pip (9.0.1)
progressbar2 (3.34.3)
protobuf (3.4.0)
pyglet (1.2.4)
PyOpenGL (3.1.0)
python-dateutil (2.6.1)
python-utils (2.2.0)
pyzmq (17.0.0b2)
requests (2.18.4)
scipy (0.19.1)
setuptools (27.2.0)
six (1.11.0)
tensorflow (1.4.0)
tensorflow-tensorboard (0.4.0rc2)
tqdm (4.19.4)
urllib3 (1.22)
Werkzeug (0.12.2)
wheel (0.29.0)
zmq (0.0.0)
```

**Comment by dbusbridge** [comment]
Hi @abhigenie92 - as a quick fix, commenting out the third line of `baselines/baselines/bench/__init__.py`:

```
from baselines.bench.benchmarks import *
from baselines.bench.monitor import *
# from baselines.bench.simple_bench import simple_bench
```
And then pip installing from source fixes this (`baselines.bench.simple_bench` doesn't seem to exist in `master`).
