### ISSUE TITLE
DDPG in parallel not working

### ISSUE THREAD

**Issue by arpit15** [openai/baselines#241]
I am trying to run ddpg with 8 workers. However the code hangs after 3-5 epochs. It generally seems that all but one worker has entered into training in all the cases in which code hangs. Can somebody verify or state if s/he is facing the same problem?

**Comment by kirk86** [comment]
For me the case is that I can't even execute the following:
`mpirun -np 4 python -m baselines.ddpg.main`

Error:
```
GPU (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:04:00.0, compute capability: 6.1)
2018-07-30 22:48:25.430830: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 9.56G (10268783360 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.431717: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 8.61G (9241905152 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.432596: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 7.75G (8317714432 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.433477: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 6.97G (7485942784 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.434348: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 6.27G (6737348096 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.435309: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 5.65G (6063612928 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.436169: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 5.08G (5457251328 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.437032: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 4.57G (4911525888 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.437895: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 4.12G (4420372992 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.438755: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 3.71G (3978335488 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.439614: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 3.33G (3580501760 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.440487: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 3.00G (3222451456 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.441362: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 2.70G (2900206336 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.442244: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 2.43G (2610185728 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.443114: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 2.19G (2349167104 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.443976: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 1.97G (2114250496 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.444850: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 1.77G (1902825472 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.445700: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 1.59G (1712542976 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.446565: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 1.43G (1541288704 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.447421: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 1.29G (1387159808 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.448291: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 1.16G (1248443904 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.449154: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 1.05G (1123599616 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.450027: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 964.39M (1011239680 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.450893: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 867.95M (910115840 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.451747: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 781.16M (819104256 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.452620: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 703.04M (737193984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.453495: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 632.74M (663474688 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.454363: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 569.46M (597127424 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.455231: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 512.52M (537414656 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.456104: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 461.27M (483673344 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.456982: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 415.14M (435305984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.457845: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 373.63M (391775488 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.458719: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 336.26M (352598016 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.459587: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 302.64M (317338368 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.460454: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 272.37M (285604608 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.461344: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 245.14M (257044224 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.462190: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 220.62M (231340032 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.463063: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 198.56M (208206080 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.463936: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 178.70M (187385600 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.464818: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 160.83M (168647168 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.465692: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 144.75M (151782656 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.467168: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 130.28M (136604416 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.468134: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 117.25M (122944000 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.469019: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 105.52M (110649600 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.469901: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 94.97M (99584768 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.470773: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 85.47M (89626368 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.471627: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 76.93M (80663808 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.472650: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 69.23M (72597504 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.473516: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 62.31M (65337856 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.474391: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 56.08M (58804224 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.475258: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 50.47M (52923904 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.476141: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 45.42M (47631616 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.477048: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 40.88M (42868480 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.478668: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 36.79M (38581760 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.480185: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 33.11M (34723584 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-07-30 22:48:25.481828: E tensorflow/stream_executor/cuda/cuda_driver.cc:927] failed to allocate 29.80M (31251456 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY


Traceback (most recent call last):
  File "/home/user/envs/rl/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/home/user/envs/rl/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/user/envs/rl/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: Blas GEMM launch failed : a.shape=(1, 17), b.shape=(17, 64), m=1, n=64, k=17
	 [[Node: critic_1/dense/MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](clip_by_value, critic/dense/kernel/read)]]

During handling of the above exception, another exception occurred:
```
Any hints?

**Comment by JunaidRana** [comment]
i am trying to run train model command using active session. 
Got this error...

`ConnectionError: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/attributes/keep_alive_token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021E55C51D68>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))`


Need help to resolve this issue.
