### ISSUE TITLE
dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by taochenshh** [openai/baselines#245]
I am using python 3.5, Tensorflow 1.4. When I tried to run ddpg example, the following error occurred:
```python
Traceback (most recent call last):
  File "/home/taochen/software/baselines/baselines/ddpg/main.py", line 128, in <module>
    run(**args)
  File "/home/taochen/software/baselines/baselines/ddpg/main.py", line 29, in run
    env = gym.make(env_id)
  File "/home/taochen/software/gym/gym/envs/registration.py", line 164, in make
    return registry.make(id)
  File "/home/taochen/software/gym/gym/envs/registration.py", line 122, in make
    env = spec.make()
  File "/home/taochen/software/gym/gym/envs/registration.py", line 88, in make
    cls = load(self._entry_point)
  File "/home/taochen/software/gym/gym/envs/registration.py", line 17, in load
    result = entry_point.load(False)
  File "/home/taochen/software/anaconda2/envs/rllab3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2409, in load
    return self.resolve()
  File "/home/taochen/software/anaconda2/envs/rllab3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2415, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/taochen/software/gym/gym/envs/mujoco/__init__.py", line 1, in <module>
    from gym.envs.mujoco.mujoco_env import MujocoEnv
  File "/home/taochen/software/gym/gym/envs/mujoco/mujoco_env.py", line 11, in <module>
    import mujoco_py
  File "/home/taochen/software/anaconda2/envs/rllab3/lib/python3.5/site-packages/mujoco_py/__init__.py", line 4, in <module>
    from .mjviewer import MjViewer
  File "/home/taochen/software/anaconda2/envs/rllab3/lib/python3.5/site-packages/mujoco_py/mjviewer.py", line 7, in <module>
    from . import mjcore, mjconstants, glfw
  File "/home/taochen/software/anaconda2/envs/rllab3/lib/python3.5/site-packages/mujoco_py/mjcore.py", line 6, in <module>
    from .mjlib import mjlib
  File "/home/taochen/software/anaconda2/envs/rllab3/lib/python3.5/site-packages/mujoco_py/mjlib.py", line 21, in <module>
    mjlib = cdll.LoadLibrary(os.path.abspath(libfile))
  File "/home/taochen/software/anaconda2/envs/rllab3/lib/python3.5/ctypes/__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "/home/taochen/software/anaconda2/envs/rllab3/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen: cannot load any more object with static TLS
```

**Comment by liziniu** [comment]
I have the same problem with python3.6 and mujoco_py 1.5.

Anyone can give some help?
