### ISSUE TITLE
a2c/run_atari.py module error

### ISSUE THREAD

**Issue by AztecoX** [openai/baselines#278]
The commit 9fa8e1baf1d1f975b87b369a8082122eac812eb1 seems to be the culprit of the following error while trying to run a a2c/run_atari.py training session (ubuntu 16.04, tensorflow-gpu 1.5.0):

Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File ".../baselines/common/vec_env/subproc_vec_env.py", line 8, in worker
    env = env_fn_wrapper.x()
  File ".../baselines/common/cmd_util.py", line 24, in _thunk
    return wrap_deepmind(env, **wrapper_kwargs)
  File ".../baselines/common/atari_wrappers.py", line 217, in wrap_deepmind
    env = WarpFrame(env)
  File ".../baselines/common/atari_wrappers.py", line 139, in __init__
    shape=(self.height, self.width, 1), dtype=np.uint8)
TypeError: __init__() got an unexpected keyword argument 'dtype'

If reverted to a commit before the one mentioned above, the algorithm works properly. I may be wrong also, not that proficient in python. It is also a first testing script (also mentioned in readme) for people who want to try out openai a2c, so I think it should be modified with care. Correct me if I am wrong with this issue, please! :)

**Comment by olegklimov** [comment]
Please try to upgrade `gym`.
