### ISSUE TITLE
__init__() got an unexpected keyword argument 'dtype'

### ISSUE THREAD

**Issue by kkjh0723** [openai/baselines#286]
I follow the install procedure in the README page and run a2c as following,
    
    CUDA_VISIBLE_DEVICES=0 python -m baselines.a2c.run_atari

Then I got this error,

    Logging to /tmp/openai-2018-02-12-20-39-52-809424
    Process Process-2:
    Traceback (most recent call last):
      File "/home/jinhyung/anaconda3/envs/py35/lib/python3.5/multiprocessing/process.py", line 252, in _bootstrap
        self.run()
      File "/home/jinhyung/anaconda3/envs/py35/lib/python3.5/multiprocessing/process.py", line 93, in run
        self._target(*self._args, **self._kwargs)
      File "/home/jinhyung/Git/py35/baselines/baselines/common/vec_env/subproc_vec_env.py", line 8, in worker
        env = env_fn_wrapper.x()
      File "/home/jinhyung/Git/py35/baselines/baselines/common/cmd_util.py", line 24, in _thunk
    return wrap_deepmind(env, **wrapper_kwargs)
      File "/home/jinhyung/Git/py35/baselines/baselines/common/atari_wrappers.py", line 217, in wrap_deepmind
        env = WarpFrame(env)
      File "/home/jinhyung/Git/py35/baselines/baselines/common/atari_wrappers.py", line 139, in __init__
    shape=(self.height, self.width, 1), dtype=np.uint8)
    TypeError: __init__() got an unexpected keyword argument 'dtype'
    
    ...
    
    Traceback (most recent call last):
      File "/home/jinhyung/anaconda3/envs/py35/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
      File "/home/jinhyung/anaconda3/envs/py35/lib/python3.5/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/home/jinhyung/Git/py35/baselines/baselines/a2c/run_atari.py", line 30, in <module>
        main()
      File "/home/jinhyung/Git/py35/baselines/baselines/a2c/run_atari.py", line 27, in main
        policy=args.policy, lrschedule=args.lrschedule, num_env=16)
      File "/home/jinhyung/Git/py35/baselines/baselines/a2c/run_atari.py", line 16, in train
        env = VecFrameStack(make_atari_env(env_id, num_env, seed), 4)
      File "/home/jinhyung/Git/py35/baselines/baselines/common/cmd_util.py", line 27, in make_atari_env
        return SubprocVecEnv([make_env(i + start_index) for i in range(num_env)])
      File "/home/jinhyung/Git/py35/baselines/baselines/common/vec_env/subproc_vec_env.py", line 49, in __init__
        observation_space, action_space = self.remotes[0].recv()
      File "/home/jinhyung/anaconda3/envs/py35/lib/python3.5/multiprocessing/connection.py", line 250, in recv
        buf = self._recv_bytes()
      File "/home/jinhyung/anaconda3/envs/py35/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
        buf = self._recv(4)
      File "/home/jinhyung/anaconda3/envs/py35/lib/python3.5/multiprocessing/connection.py", line 379, in _recv
        chunk = read(handle, remaining)
    ConnectionResetError: [Errno 104] Connection reset by peer

How can I fix this?

**Comment by zishanahmed08** [comment]
Update gym to the latest version

**Comment by kkjh0723** [comment]
Thanks @zishanahmed08, upgrading gym solves the problem.
