### ISSUE TITLE
Is LSTM policy in PPO2 working correctly?

### ISSUE THREAD

**Issue by harry2636** [openai/baselines#294]
I tried on LSTM policy of PPO2 (with default hyper-parameter) in PongNoFrameSkipv4 environment but, it failed to improve the reward. It stuck at the minimum reward -21. I also tried on different nsteps value (4 and 1024) but it failed to.

However, when I  tried on CNN policy of PPO2 (also with default hyper-parameter), it succeeded to converge to the maximum reward of 21.

Is LSTM policy in PPO2 working correctly?

**Comment by Guiadan** [comment]
worked perfect for me, on a different task. you can try to adjust network architecture to the task you're trying to solve. try changing the conv layers size rather than just changing the nsteps parameter.

**Comment by harry2636** [comment]
@Guiadan Thanks! I will try it out.

**Comment by davsuacar** [comment]
I tried on CNNPolicy in SonicTheHedgehog-Genesis and it works perfectly but when I tried to run LstmPolicy I got the following error:

```python

Traceback (most recent call last):
  File "/Users/david.suarez/Work/i+d/sonic-rl/.venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1567, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot reshape a tensor with 262144 elements to shape [0,4096,?] (0 elements) for 'model_1/Reshape_1' (op: 'Reshape') with input shapes: [512,512], [3] and with input tensors computed as partial shapes: input[1] = [0,4096,?].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/david.suarez/Work/i+d/sonic-rl/ppo/ppo_agent.py", line 41, in <module>
    main()
  File "/Users/david.suarez/Work/i+d/sonic-rl/ppo/ppo_agent.py", line 36, in main
    total_timesteps=int(1e7)
  File "/Users/david.suarez/Work/i+d/sonic-rl/baselines/baselines/ppo2/ppo2.py", line 175, in learn
    model = make_model()
  File "/Users/david.suarez/Work/i+d/sonic-rl/baselines/baselines/ppo2/ppo2.py", line 170, in <lambda>
    max_grad_norm=max_grad_norm)
  File "/Users/david.suarez/Work/i+d/sonic-rl/baselines/baselines/ppo2/ppo2.py", line 18, in __init__
    train_model = policy(sess, ob_space, ac_space, nbatch_train, nsteps, reuse=True)
  File "/Users/david.suarez/Work/i+d/sonic-rl/baselines/baselines/ppo2/policies.py", line 65, in __init__
    xs = batch_to_seq(h, nenv, nsteps)
  File "/Users/david.suarez/Work/i+d/sonic-rl/baselines/baselines/a2c/utils.py", line 74, in batch_to_seq
    h = tf.reshape(h, [nbatch, nsteps, -1])
  File "/Users/david.suarez/Work/i+d/sonic-rl/.venv/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 6113, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/Users/david.suarez/Work/i+d/sonic-rl/.venv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/david.suarez/Work/i+d/sonic-rl/.venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/Users/david.suarez/Work/i+d/sonic-rl/.venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1734, in __init__
    control_input_ops)
  File "/Users/david.suarez/Work/i+d/sonic-rl/.venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1570, in _create_c_op
    raise ValueError(str(e))
ValueError: Cannot reshape a tensor with 262144 elements to shape [0,4096,?] (0 elements) for 'model_1/Reshape_1' (op: 'Reshape') with input shapes: [512,512], [3] and with input tensors computed as partial shapes: input[1] = [0,4096,?].

```


**Here is my main code:**

```python

import tensorflow as tf

from baselines.common.vec_env.dummy_vec_env import DummyVecEnv
import baselines.ppo2.ppo2 as ppo2
import baselines.ppo2.policies as policies

from sonic_util import make_env


def main():
    """Run PPO until the environment throws an exception."""
    config = tf.ConfigProto()
    config.gpu_options.allow_growth = True # pylint: disable=E1101
    with tf.Session(config=config):
        # Take more timesteps than we need to be sure that
        # we stop due to an exception.

        env = DummyVecEnv([make_env])

        ppo2.learn(policy=policies.LstmPolicy,
                   env=env,
                   nsteps=4096,
                   nminibatches=8,
                   lam=0.95,
                   gamma=0.99,
                   noptepochs=3,
                   log_interval=1,
                   ent_coef=0.01,
                   lr=lambda _: 2e-4,
                   cliprange=lambda _: 0.1,
                   total_timesteps=int(1e7)
                   )

if __name__ == '__main__':

    main()
```
