### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by moshebeutel** [openai/baselines#318]
hi 
I have problems installing package
I am using an Ubuntu 16.04 python 3.6.4
after cloning and 
pip install -e .
I get:
Obtaining file:///home/iaiai/baselines
Collecting gym[atari,classic_control,mujoco,robotics] (from baselines==0.1.5)
Requirement already satisfied: scipy in /home/iaiai/anaconda3/lib/python3.6/site-packages (from baselines==0.1.5)
Requirement already satisfied: tqdm in /home/iaiai/anaconda3/lib/python3.6/site-packages (from baselines==0.1.5)
Requirement already satisfied: joblib in /home/iaiai/anaconda3/lib/python3.6/site-packages (from baselines==0.1.5)
Requirement already satisfied: zmq in /home/iaiai/anaconda3/lib/python3.6/site-packages (from baselines==0.1.5)
Requirement already satisfied: dill in /home/iaiai/anaconda3/lib/python3.6/site-packages (from baselines==0.1.5)
Requirement already satisfied: progressbar2 in /home/iaiai/anaconda3/lib/python3.6/site-packages (from baselines==0.1.5)
Requirement already satisfied: mpi4py in /home/iaiai/anaconda3/lib/python3.6/site-packages (from baselines==0.1.5)
Requirement already satisfied: cloudpickle in /home/iaiai/anaconda3/lib/python3.6/site-packages (from baselines==0.1.5)
Requirement already satisfied: tensorflow>=1.4.0 in /home/iaiai/anaconda3/lib/python3.6/site-packages (from baselines==0.1.5)
Requirement already satisfied: click in /home/iaiai/anaconda3/lib/python3.6/site-packages (from baselines==0.1.5)
Requirement already satisfied: numpy>=1.10.4 in /home/iaiai/anaconda3/lib/python3.6/site-packages (from gym[atari,classic_control,mujoco,robotics]->baselines==0.1.5)
Requirement already satisfied: six in /home/iaiai/anaconda3/lib/python3.6/site-packages (from gym[atari,classic_control,mujoco,robotics]->baselines==0.1.5)
Requirement already satisfied: pyglet>=1.2.0 in /home/iaiai/anaconda3/lib/python3.6/site-packages (from gym[atari,classic_control,mujoco,robotics]->baselines==0.1.5)
Requirement already satisfied: requests>=2.0 in /home/iaiai/anaconda3/lib/python3.6/site-packages (from gym[atari,classic_control,mujoco,robotics]->baselines==0.1.5)
Collecting atari-py>=0.1.1; extra == "atari" (from gym[atari,classic_control,mujoco,robotics]->baselines==0.1.5)
  Using cached atari-py-0.1.1.tar.gz
Requirement already satisfied: PyOpenGL; extra == "atari" in /home/iaiai/anaconda3/lib/python3.6/site-packages (from gym[atari,classic_control,mujoco,robotics]->baselines==0.1.5)
Requirement already satisfied: Pillow; extra == "atari" in /home/iaiai/anaconda3/lib/python3.6/site-packages (from gym[atari,classic_control,mujoco,robotics]->baselines==0.1.5)
Requirement already satisfied: imageio; extra == "mujoco" in /home/iaiai/anaconda3/lib/python3.6/site-packages (from gym[atari,classic_control,mujoco,robotics]->baselines==0.1.5)
Collecting mujoco-py>=1.50; extra == "mujoco" (from gym[atari,classic_control,mujoco,robotics]->baselines==0.1.5)
  Using cached mujoco-py-1.50.1.41.tar.gz
Requirement already satisfied: pyzmq in /home/iaiai/anaconda3/lib/python3.6/site-packages (from zmq->baselines==0.1.5)
Requirement already satisfied: python-utils>=2.3.0 in /home/iaiai/anaconda3/lib/python3.6/site-packages (from progressbar2->baselines==0.1.5)
Requirement already satisfied: protobuf>=3.4.0 in /home/iaiai/anaconda3/lib/python3.6/site-packages (from tensorflow>=1.4.0->baselines==0.1.5)
Requirement already satisfied: astor>=0.6.0 in /home/iaiai/anaconda3/lib/python3.6/site-packages (from tensorflow>=1.4.0->baselines==0.1.5)
Requirement already satisfied: wheel>=0.26 in /home/iaiai/anaconda3/lib/python3.6/site-packages (from tensorflow>=1.4.0->baselines==0.1.5)
Requirement already satisfied: absl-py>=0.1.6 in /home/iaiai/anaconda3/lib/python3.6/site-packages (from tensorflow>=1.4.0->baselines==0.1.5)
Requirement already satisfied: termcolor>=1.1.0 in /home/iaiai/anaconda3/lib/python3.6/site-packages (from tensorflow>=1.4.0->baselines==0.1.5)
Requirement already satisfied: grpcio>=1.8.6 in /home/iaiai/anaconda3/lib/python3.6/site-packages (from tensorflow>=1.4.0->baselines==0.1.5)
Requirement already satisfied: tensorboard<1.7.0,>=1.6.0 in /home/iaiai/anaconda3/lib/python3.6/site-packages (from tensorflow>=1.4.0->baselines==0.1.5)
Requirement already satisfied: gast>=0.2.0 in /home/iaiai/anaconda3/lib/python3.6/site-packages (from tensorflow>=1.4.0->baselines==0.1.5)
Requirement already satisfied: future in /home/iaiai/anaconda3/lib/python3.6/site-packages (from pyglet>=1.2.0->gym[atari,classic_control,mujoco,robotics]->baselines==0.1.5)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/iaiai/anaconda3/lib/python3.6/site-packages (from requests>=2.0->gym[atari,classic_control,mujoco,robotics]->baselines==0.1.5)
Requirement already satisfied: idna<2.7,>=2.5 in /home/iaiai/anaconda3/lib/python3.6/site-packages (from requests>=2.0->gym[atari,classic_control,mujoco,robotics]->baselines==0.1.5)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /home/iaiai/anaconda3/lib/python3.6/site-packages (from requests>=2.0->gym[atari,classic_control,mujoco,robotics]->baselines==0.1.5)
Requirement already satisfied: certifi>=2017.4.17 in /home/iaiai/anaconda3/lib/python3.6/site-packages (from requests>=2.0->gym[atari,classic_control,mujoco,robotics]->baselines==0.1.5)
Collecting glfw>=1.4.0 (from mujoco-py>=1.50; extra == "mujoco"->gym[atari,classic_control,mujoco,robotics]->baselines==0.1.5)
Requirement already satisfied: Cython>=0.27.2 in /home/iaiai/anaconda3/lib/python3.6/site-packages (from mujoco-py>=1.50; extra == "mujoco"->gym[atari,classic_control,mujoco,robotics]->baselines==0.1.5)
Requirement already satisfied: cffi>=1.10 in /home/iaiai/anaconda3/lib/python3.6/site-packages (from mujoco-py>=1.50; extra == "mujoco"->gym[atari,classic_control,mujoco,robotics]->baselines==0.1.5)
Requirement already satisfied: setuptools in /home/iaiai/anaconda3/lib/python3.6/site-packages (from protobuf>=3.4.0->tensorflow>=1.4.0->baselines==0.1.5)
Requirement already satisfied: html5lib==0.9999999 in /home/iaiai/anaconda3/lib/python3.6/site-packages (from tensorboard<1.7.0,>=1.6.0->tensorflow>=1.4.0->baselines==0.1.5)
Requirement already satisfied: markdown>=2.6.8 in /home/iaiai/anaconda3/lib/python3.6/site-packages (from tensorboard<1.7.0,>=1.6.0->tensorflow>=1.4.0->baselines==0.1.5)
Requirement already satisfied: werkzeug>=0.11.10 in /home/iaiai/anaconda3/lib/python3.6/site-packages (from tensorboard<1.7.0,>=1.6.0->tensorflow>=1.4.0->baselines==0.1.5)
Requirement already satisfied: bleach==1.5.0 in /home/iaiai/anaconda3/lib/python3.6/site-packages (from tensorboard<1.7.0,>=1.6.0->tensorflow>=1.4.0->baselines==0.1.5)
Requirement already satisfied: pycparser in /home/iaiai/anaconda3/lib/python3.6/site-packages (from cffi>=1.10->mujoco-py>=1.50; extra == "mujoco"->gym[atari,classic_control,mujoco,robotics]->baselines==0.1.5)
Building wheels for collected packages: atari-py, mujoco-py
  Running setup.py bdist_wheel for atari-py ... error
  Complete output from command /home/iaiai/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-d4x95a5i/atari-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp_kse5m4upip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  make: Entering directory '/tmp/pip-build-d4x95a5i/atari-py/atari_py/ale_interface'
  mkdir -p build && cd build && cmake .. && make -j4
  /bin/sh: 1: cmake: not found
  Makefile:4: recipe for target 'build' failed
  make: *** [build] Error 127
  make: Leaving directory '/tmp/pip-build-d4x95a5i/atari-py/atari_py/ale_interface'
  Could not build atari-py: Command '['make', 'build', '-C', 'atari_py/ale_interface', '-j', '7']' returned non-zero exit status 2.. (HINT: are you sure cmake is installed? You might also be missing a library. Atari-py requires: zlib [installable as 'apt-get install zlib1g-dev' on Ubuntu].)
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-d4x95a5i/atari-py/setup.py", line 36, in <module>
      tests_require=['nose2']
    File "/home/iaiai/anaconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/home/iaiai/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/iaiai/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/home/iaiai/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/iaiai/anaconda3/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 204, in run
      self.run_command('build')
    File "/home/iaiai/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/iaiai/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-d4x95a5i/atari-py/setup.py", line 16, in run
      subprocess.check_call(cmd)
    File "/home/iaiai/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['make', 'build', '-C', 'atari_py/ale_interface', '-j', '7']' returned non-zero exit status 2.

  ----------------------------------------
  Failed building wheel for atari-py
  Running setup.py clean for atari-py
  Running setup.py bdist_wheel for mujoco-py ... error
  Complete output from command /home/iaiai/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-d4x95a5i/mujoco-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp4zcj548hpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  Compiling /tmp/pip-build-d4x95a5i/mujoco-py/mujoco_py/cymj.pyx because it changed.
  [1/1] Cythonizing /tmp/pip-build-d4x95a5i/mujoco-py/mujoco_py/cymj.pyx
  running build_ext
  building 'mujoco_py.cymj' extension
  creating /tmp/pip-build-d4x95a5i/mujoco-py/mujoco_py/generated/_pyxbld_LinuxExtensionBuilder
  creating /tmp/pip-build-d4x95a5i/mujoco-py/mujoco_py/generated/_pyxbld_LinuxExtensionBuilder/temp.linux-x86_64-3.6
  creating /tmp/pip-build-d4x95a5i/mujoco-py/mujoco_py/generated/_pyxbld_LinuxExtensionBuilder/temp.linux-x86_64-3.6/tmp
  creating /tmp/pip-build-d4x95a5i/mujoco-py/mujoco_py/generated/_pyxbld_LinuxExtensionBuilder/temp.linux-x86_64-3.6/tmp/pip-build-d4x95a5i
  creating /tmp/pip-build-d4x95a5i/mujoco-py/mujoco_py/generated/_pyxbld_LinuxExtensionBuilder/temp.linux-x86_64-3.6/tmp/pip-build-d4x95a5i/mujoco-py
  creating /tmp/pip-build-d4x95a5i/mujoco-py/mujoco_py/generated/_pyxbld_LinuxExtensionBuilder/temp.linux-x86_64-3.6/tmp/pip-build-d4x95a5i/mujoco-py/mujoco_py
  creating /tmp/pip-build-d4x95a5i/mujoco-py/mujoco_py/generated/_pyxbld_LinuxExtensionBuilder/temp.linux-x86_64-3.6/tmp/pip-build-d4x95a5i/mujoco-py/mujoco_py/gl
  gcc -pthread -B /home/iaiai/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Imujoco_py -I/tmp/pip-build-d4x95a5i/mujoco-py/mujoco_py -I/home/iaiai/.mujoco/mjpro150/include -I/home/iaiai/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/tmp/pip-build-d4x95a5i/mujoco-py/mujoco_py/vendor/egl -I/home/iaiai/anaconda3/include/python3.6m -c /tmp/pip-build-d4x95a5i/mujoco-py/mujoco_py/cymj.c -o /tmp/pip-build-d4x95a5i/mujoco-py/mujoco_py/generated/_pyxbld_LinuxExtensionBuilder/temp.linux-x86_64-3.6/tmp/pip-build-d4x95a5i/mujoco-py/mujoco_py/cymj.o -fopenmp -w
  /tmp/pip-build-d4x95a5i/mujoco-py/mujoco_py/cymj.c:568:21: fatal error: mjmodel.h: No such file or directory
  compilation terminated.
  error: command 'gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for mujoco-py
  Running setup.py clean for mujoco-py
Failed to build atari-py mujoco-py
Installing collected packages: atari-py, glfw, mujoco-py, gym, baselines
  Running setup.py install for atari-py ... error
    Complete output from command /home/iaiai/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-d4x95a5i/atari-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-39rkf867-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    make: Entering directory '/tmp/pip-build-d4x95a5i/atari-py/atari_py/ale_interface'
    mkdir -p build && cd build && cmake .. && make -j4
    /bin/sh: 1: cmake: not found
    Makefile:4: recipe for target 'build' failed
    make: *** [build] Error 127
    make: Leaving directory '/tmp/pip-build-d4x95a5i/atari-py/atari_py/ale_interface'
    Could not build atari-py: Command '['make', 'build', '-C', 'atari_py/ale_interface', '-j', '7']' returned non-zero exit status 2.. (HINT: are you sure cmake is installed? You might also be missing a library. Atari-py requires: zlib [installable as 'apt-get install zlib1g-dev' on Ubuntu].)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-d4x95a5i/atari-py/setup.py", line 36, in <module>
        tests_require=['nose2']
      File "/home/iaiai/anaconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/home/iaiai/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/iaiai/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/iaiai/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/iaiai/anaconda3/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/iaiai/anaconda3/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/iaiai/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/iaiai/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-d4x95a5i/atari-py/setup.py", line 16, in run
        subprocess.check_call(cmd)
      File "/home/iaiai/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', 'build', '-C', 'atari_py/ale_interface', '-j', '7']' returned non-zero exit status 2.

    ----------------------------------------
Command "/home/iaiai/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-d4x95a5i/atari-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-39rkf867-record/install-record.txt --single-version-externally-managed --compile" failed with error code1 in /tmp/pip-build-d4x95a5i/atari-py/

Following the thread:
https://github.com/chris-chris/pysc2-examples/issues/4 and 
https://github.com/openai/gym/issues/218
I already installed  xvfb libav-tools xorg-dev libsdl2-dev swig cmake

still not working.... :(

thnx a lot

**Comment by DefinitelyMaybe** [comment]
"HINT: are you sure cmake is installed? You might also be missing a library. Atari-py requires: zlib [installable as 'apt-get install zlib1g-dev' on Ubuntu"

Anyone got zlib on windows? how to?
