### ISSUE TITLE
Fix bug in Deepq module import error

### ISSUE THREAD

**Issue by fstonezst** [openai/baselines#351]
There is a module import bug in the deepq.sample.
from baselines import deepq should be modify to from baselines.deepq import build_graph
the function build_act is write in the build_graph not in the init file.
(#352)

==================================
python train_cartpole.py 
Traceback (most recent call last):
  File "train_cartpole.py", line 3, in <module>
    from baselines import deepq
  File "/home/peter/Downloads/baselines/baselines/deepq/__init__.py", line 3, in <module>
    from baselines.deepq.simple import learn, load  # noqa
  File "/home/peter/Downloads/baselines/baselines/deepq/simple.py", line 13, in <module>
    from baselines import deepq
ImportError: cannot import name 'deepq'

**Comment by pzhokhov** [comment]
@fstonezst should be fixed now, please reopen if you still face the issue
