### ISSUE TITLE
PPO2 - tuple index out of range when using Discrete action state. 

### ISSUE THREAD

**Issue by redknightlois** [openai/baselines#364]
I have a gym.spaces.Discrete(3) action space on my environment but when I try to execute PPO2 latest code (built from source), I get:
```
Traceback (most recent call last):
  File "E:/Src/trendstone-git/src/learner-v2/train.py", line 143, in <module>
    total_timesteps=max_timesteps)
  File "C:\Anaconda3\lib\site-packages\baselines\ppo2\ppo2.py", line 178, in learn
    model = make_model()
  File "C:\Anaconda3\lib\site-packages\baselines\ppo2\ppo2.py", line 173, in <lambda>
    max_grad_norm=max_grad_norm)
  File "C:\Anaconda3\lib\site-packages\baselines\ppo2\ppo2.py", line 16, in __init__
    act_model = policy(sess, ob_space, ac_space, nbatch_act, 1, reuse=False)
  File "C:\Anaconda3\lib\site-packages\baselines\ppo2\policies.py", line 135, in __init__
    actdim = ac_space.shape[0]
IndexError: tuple index out of range
```

Given that `gym.spaces.Discrete` does not implement `.shape` I workaround it creating an inherited class and returning `(1,)` but I am wondering if I am not making things wrong. 

EDIT: Moreover now it will only sample actions as 0 and 1. When I put (2,) it will sample between 0 and 3.  Any idea why this is not happening would be welcome.

**Comment by unixpickle** [comment]
It looks like MlpPolicy is designed for continuous action spaces, and CnnPolicy is designed for discrete action spaces. It should be fairly easy to take the logic from CnnPolicy and move it to MlpPolicy. E.g. change `actdim = ac_space.shape[0]` to `actdim = ac_space.n`.

**Comment by pzhokhov** [comment]
this should be addressed now, I'll close the issue. @redknightlois please reopen if you still experience the problem.
