### ISSUE TITLE
Program Fails in def log.

### ISSUE THREAD

**Issue by maplewizard** [openai/baselines#37]
Hi, I am using baselines by installing with pip, and run `python -m baselines.deepq.experiments.train_cartpole`, but I encountered with:
```
Traceback (most recent call last):
  File "/Users/swacg/anaconda2/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/Users/swacg/anaconda2/lib/python2.7/runpy.py", line 102, in _get_module_details
    loader = get_loader(mod_name)
  File "/Users/swacg/anaconda2/lib/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "/Users/swacg/anaconda2/lib/python2.7/pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "/Users/swacg/anaconda2/lib/python2.7/pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "baselines/deepq/__init__.py", line 4, in <module>
    from baselines.deepq.simple import learn, load  # noqa
  File "baselines/deepq/simple.py", line 10, in <module>
    from baselines import logger
  File "baselines/logger.py", line 139
    def log(*args, level=INFO):
                       ^
SyntaxError: invalid syntax
```
How can I solve that?

**Comment by mirceamironenco** [comment]
Are you using Python 3.5+? I believe you can't pass regular parameters after * in Python 2.7. I assume baselines only supports Python 3.

**Comment by sarathmenon-downey** [comment]
Use python -m baselines.deepq.experiments.train_cartpole.
Only python3 works
