### ISSUE TITLE
HER reshape error

### ISSUE THREAD

**Issue by aman-tiwari** [openai/baselines#382]
I'm getting this error:
```python-traceback
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    main()
  File "/home/studio/miniconda3/envs/py35/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/studio/miniconda3/envs/py35/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/studio/miniconda3/envs/py35/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/studio/miniconda3/envs/py35/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "train.py", line 180, in main
    launch(**kwargs)
  File "train.py", line 167, in launch
    policy_save_interval=policy_save_interval, save_policies=save_policies)
  File "train.py", line 41, in train
    policy.store_episode(episode)
  File "/home/studio/Documents/aman/pictogram_agents/baselines/baselines/her/ddpg.py", line 154, in store_episode
    transitions = self.sample_transitions(episode_batch, num_normalizing_transitions)
  File "/home/studio/Documents/aman/pictogram_agents/baselines/baselines/her/her.py", line 59, in _sample_her_transitions
    transitions[k].reshape(batch_size, *transitions[k].shape[1:])
ValueError: cannot reshape array of size 1 into shape (2000,)
```

With the environment, the MuJoCo model is a starfish-like agent with 24 joints trying to get to a target location.

```python3
class FindTargetHER(robot_env.RobotEnv):
    ''' same as FindTarget except as as a RobotEnv  '''
    
    def __init__(self, reward_type='sparse', distance_threshold=0.5):
        self.reward_type = reward_type
        self.distance_threshold = distance_threshold
        super(FindTargetHER, self).__init__(
            model_path=os.path.dirname(__file__) + '/assets/starfish_novis.xml',
            n_substeps=20, 
            initial_qpos={}, 
            n_actions=24)

    def compute_reward(self, achieved_goal, goal, info):
        dist = np.square(achieved_goal - goal).sum()
        if self.reward_type == 'sparse':
            return -(dist > self.distance_threshold).astype(np.float32)
        else:
            return -dist

    def _set_action(self, action):
        self.sim.data.ctrl[:] = action 

    def _body_pos_by_name(self, name):
        return self.sim.data.body_xpos[self.sim.model.body_name2id(name)]

    def _get_obs(self):
        self_pos = self._body_pos_by_name('agent0/root')
        target_pos = self._body_pos_by_name('target')
        dist_to_target = self_pos - target_pos

        joint_vel = self.sim.data.qvel[:]
        joint_pos = self.sim.data.qpos.flat[:]
        
        obs = OrderedDict({
            'observation': np.concatenate((dist_to_target, target_pos, joint_vel, joint_pos)),
            'desired_goal': target_pos,
            'achieved_goal': self_pos
        })
        
        return obs
        
    def _is_success(self, achieved_goal, desired_goal):
        dist = np.square(achieved_goal - desired_goal).sum()
        return (dist < self.distance_threshold).astype(np.float32)


    def _sample_goal(self):
        init_torso = self._body_pos_by_name('agent0/root')
        radius = self.distance_threshold * 4.0
        goal = init_torso + self.np_random.uniform(-radius, radius, size=3)
        target_id = self.sim.model.body_name2id('target')
        self.sim.data.body_xpos[target_id] = goal.copy()
        return goal.copy()
```

**Comment by aman-tiwari** [comment]
I just realised it was caused by `_is_success` not working correctly for batched inputs (I didn't realise it will be caused by batched inputs, is this documented anywhere?)

The correct way to do this (as the examples in the fetch environment does it)
```python3
def goal_distance(goal_a, goal_b):
    assert goal_a.shape == goal_b.shape
    return np.linalg.norm(goal_a - goal_b, axis=-1)

class FindTargetHER(robot_env.RobotEnv):

... other stuff ...

    def compute_reward(self, achieved_goal, goal, info):
        dist = goal_distance(achieved_goal, goal)
        if self.reward_type == 'sparse':
            return -(dist > self.distance_threshold).astype(np.float32)
        else:
            return -dist

    def _is_success(self, achieved_goal, desired_goal):
        dist = goal_distance(achieved_goal, desired_goal)
        return (dist < self.distance_threshold).astype(np.float32)
```
