### ISSUE TITLE
No Module named baselines.common.runners

### ISSUE THREAD

**Issue by marcinic** [openai/baselines#391]
Traceback (most recent call last):
  File "/root/compo/agent.py", line 4, in <module>
    import baselines.ppo2.ppo2 as ppo2
  File "/root/venv/lib/python3.5/site-packages/baselines/ppo2/ppo2.py", line 10, in <module>
    from baselines.common.runners import AbstractEnvRunner
ImportError: No module named 'baselines.common.runners'

Referenced in issue #386

**Comment by marcinic** [comment]
Relates to an unapproved pull request #389

**Comment by pzhokhov** [comment]
@marcinic correct, should be fixed when https://github.com/openai/baselines/pull/389 goes in
