### ISSUE TITLE
PPO: run atari OOM

### ISSUE THREAD

**Issue by dmuestc** [openai/baselines#395]
Hi，all,
  Run ppo2, use the default config, and run on a single GPU machine，: "python run_atari.py"
  after running 71680 timesteps, go out OOM,

 **here is my GPU configuration:**
![image](https://user-images.githubusercontent.com/31580105/39737266-cce62aca-52b6-11e8-9d54-a4947e4a39a9.png)

 **and here is the log:**

--------------------------------------
1061 | approxkl           | 0.0015566408  |
1062 | clipfrac           | 0.079833984   |
1063 | eplenmean          | 208           |
1064 | eprewmean          | 2.04          |
1065 | explained_variance | 0.892         |
1066 | fps                | 584           |
1067 | nupdates           | 70            |
1068 | policy_entropy     | 1.353787      |
1069 | policy_loss        | -0.0040352196 |
1070 | serial_timesteps   | 8960          |
1071 | time_elapsed       | 127           |
1072 | total_timesteps    | 71680         |
1073 | value_loss         | 0.011804908   |
1074 --------------------------------------
1075 2018-05-08 11:13:52.489906: W tensorflow/core/common_runtime/bfc_allocator.cc:273] Allocator (GPU_0_bfc) ran out of memory trying to allocate 27.56MiB.  Current allocation summary follows.
1076 2018-05-08 11:13:52.489992: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (256):   Total Chunks: 59, Chunks in use: 57. 14.8KiB allocated for chunks. 14.2KiB in use in bin. 3.3KiB client     -requested in use in bin.
1077 2018-05-08 11:13:52.490010: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (512):   Total Chunks: 1, Chunks in use: 0. 512B allocated for chunks. 0B in use in bin. 0B client-requested in      use in bin.
1078 2018-05-08 11:13:52.490026: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (1024):  Total Chunks: 4, Chunks in use: 4. 4.2KiB allocated for chunks. 4.2KiB in use in bin. 4.0KiB client-req     uested in use in bin.
1079 2018-05-08 11:13:52.490051: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (2048):  Total Chunks: 11, Chunks in use: 11. 22.0KiB allocated for chunks. 22.0KiB in use in bin. 22.0KiB clien     t-requested in use in bin.
1080 2018-05-08 11:13:52.490068: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (4096):  Total Chunks: 1, Chunks in use: 1. 4.0KiB allocated for chunks. 4.0KiB in use in bin. 4.0KiB client-req     uested in use in bin.

........

Traceback (most recent call last):
1256   File "run_atari.py", line 40, in <module>
1257     main()
1258   File "run_atari.py", line 37, in main
1259     policy=args.policy)
1260   File "run_atari.py", line 29, in train
1261     total_timesteps=int(num_timesteps * 1.1))
1262   File "/home/sam.dm/baselines/baselines/ppo2/ppo2.py", line 203, in learn
1263     mblossvals.append(model.train(lrnow, cliprangenow, *slices))
1264   File "/home/sam.dm/baselines/baselines/ppo2/ppo2.py", line 61, in train
1265     td_map
1266   File "/gruntdata/sam.dm/anaconda2/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
1267     run_metadata_ptr)
1268   File "/gruntdata/sam.dm/anaconda2/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1120, in _run
1269     feed_dict_tensor, options, run_metadata)
1270   File "/gruntdata/sam.dm/anaconda2/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
1271     options, run_metadata)
1272   File "/gruntdata/sam.dm/anaconda2/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
1273     raise type(e)(node_def, op, message)
1274 tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[256,4,84,84]
1275      [[Node: gradients/model_1/c1/Conv2D_grad/Conv2DBackpropFilter = Conv2DBackpropFilter[T=DT_FLOAT, data_format="NHWC", padding="VALID", strides=[1, 4, 4, 1], use_cudnn_on_gpu=true, _device="/job:l     ocalhost/replica:0/task:0/device:GPU:0"](model_1/truediv, gradients/model_1/c1/Conv2D_grad/ShapeN:1, gradients/model_1/c1/add_grad/Reshape_1)]]
1276
1277 Caused by op 'gradients/model_1/c1/Conv2D_grad/Conv2DBackpropFilter', defined at:
1278   File "run_atari.py", line 40, in <module>
1279     main()
1280   File "run_atari.py", line 37, in main
1281     policy=args.policy)
1282   File "run_atari.py", line 29, in train
1283     total_timesteps=int(num_timesteps * 1.1))
1284   File "/home/sam.dm/baselines/baselines/ppo2/ppo2.py", line 178, in learn
1285     model = make_model()
1286   File "/home/sam.dm/baselines/baselines/ppo2/ppo2.py", line 173, in <lambda>
1287     max_grad_norm=max_grad_norm)
1288   File "/home/sam.dm/baselines/baselines/ppo2/ppo2.py", line 44, in __init__
1289     grads = tf.gradients(loss, params)
1290   File "/gruntdata/sam.dm/anaconda2/envs/py36/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 581, in gradients
1291     grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
File "/gruntdata/sam.dm/anaconda2/envs/py36/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 353, in _MaybeCompile
1293     return grad_fn()  # Exit early
1294   File "/gruntdata/sam.dm/anaconda2/envs/py36/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 581, in <lambda>
1295     grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
1296   File "/gruntdata/sam.dm/anaconda2/envs/py36/lib/python3.6/site-packages/tensorflow/python/ops/nn_grad.py", line 481, in _Conv2DGrad
1297     data_format)]
1298   File "/gruntdata/sam.dm/anaconda2/envs/py36/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 704, in conv2d_backprop_filter
1299     use_cudnn_on_gpu=use_cudnn_on_gpu, data_format=data_format, name=name)
1300   File "/gruntdata/sam.dm/anaconda2/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
1301     op_def=op_def)
1302   File "/gruntdata/sam.dm/anaconda2/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
1303     op_def=op_def)
1304   File "/gruntdata/sam.dm/anaconda2/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
1305     self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
1306
1307 ...which was originally created as op 'model_1/c1/Conv2D', defined at:
1308   File "run_atari.py", line 40, in <module>
1309     main()
1310 [elided 3 identical lines from previous traceback]
1311   File "/home/sam.dm/baselines/baselines/ppo2/ppo2.py", line 173, in <lambda>
1312     max_grad_norm=max_grad_norm)
1313   File "/home/sam.dm/baselines/baselines/ppo2/ppo2.py", line 17, in __init__
1314     train_model = policy(sess, ob_space, ac_space, nbatch_train, nsteps, reuse=True)
1315   File "/home/sam.dm/baselines/baselines/ppo2/policies.py", line 108, in __init__
1316     h = nature_cnn(X)
1317   File "/home/sam.dm/baselines/baselines/ppo2/policies.py", line 12, in nature_cnn
1318     h = activ(conv(scaled_images, 'c1', nf=32, rf=8, stride=4, init_scale=np.sqrt(2)))
1319   File "/home/sam.dm/baselines/baselines/a2c/utils.py", line 59, in conv
1320     return b + tf.nn.conv2d(x, w, strides=strides, padding=pad, data_format=data_format)
1321   File "/gruntdata/sam.dm/anaconda2/envs/py36/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 631, in conv2d
1322     data_format=data_format, name=name)
1323   File "/gruntdata/sam.dm/anaconda2/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
1324     op_def=op_def)
1325   File "/gruntdata/sam.dm/anaconda2/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
1326     op_def=op_def)
1327   File "/gruntdata/sam.dm/anaconda2/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
1328     self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
1329
1330 ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[256,4,84,84]
1331      [[Node: gradients/model_1/c1/Conv2D_grad/Conv2DBackpropFilter = Conv2DBackpropFilter[T=DT_FLOAT, data_format="NHWC", padding="VALID", strides=[1, 4, 4, 1], use_cudnn_on_gpu=true, _device="/job:l     ocalhost/replica:0/task:0/device:GPU:0"](model_1/truediv, gradients/model_1/c1/Conv2D_grad/ShapeN:1, gradients/model_1/c1/add_grad/Reshape_1)]]

=====================
Anyone encountered the same issue?

**Comment by pzhokhov** [comment]
Hi @dmuestc ! By the looks of it this may be some sort of GPU memory leak in tensorflow or CUDA or driver. I am having hard time reproducing the issue though - so far I have tried with two setups:
cuda-9.0.176, tensorflow-gpu==1.8.0, python 3.6 with anaconda, and cuda-8.0.61 tensorflow-gpu==1.4.0, python 3.5 without anaconda. 
In both cases OS was ubuntu 16.04 (virtualized), and the driver version 390.30. 
Two things you could do to help with this investivation:
1. try updating drivers, cuda and tensorflow to latest version 
2. post here detailed config of your system - version and type of OS, version of cuda, version of tensorflow.
Thanks!

**Comment by pzhokhov** [comment]
Another thing I'd check - right now in ppo2.run_atari this line: https://github.com/openai/baselines/blob/9cb7ece3387c4cb680fd831f38400b356bd599a6/baselines/ppo2/run_atari.py#L19: ensures that not all the GPU RAM is occupied, but only the amount that is needed (save for fragmentation etc). run_atari should take ~800-900 Mb of GPU RAM, whereas from the output of your nvidia-smi I can see that 11G is occupied. Did it grab all 11Gb from the start or gradually expanded to that size?
