### ISSUE TITLE
Robotics env. Failure to record video

### ISSUE THREAD

**Issue by Baichenjia** [openai/baselines#411]
When I use keyboard "V" to record the Video of Env "FetchReach-v1", this is some errro!
I use debain 9 , Nvidia 390.59, cuda 9, python 3.6, tensorflow 1.8

Traceback (most recent call last):
  File "play.py", line 60, in <module>
    main()
  File "/opt/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "play.py", line 51, in main
    evaluator.generate_rollouts()
  File "/home/chenjia/Workspace/reinforcement_learning/baselines/baselines/her/rollout.py", line 141, in generate_rollouts
    self.envs[i].render()
  File "/home/chenjia/Workspace/reinforcement_learning/gym/gym/core.py", line 284, in render
    return self.env.render(mode)
  File "/home/chenjia/Workspace/reinforcement_learning/gym/gym/envs/robotics/robot_env.py", line 99, in render
    self._get_viewer().render()
  File "/home/chenjia/mujoco-py/mujoco_py/mjviewer.py", line 202, in render
    render_inner_loop(self)
  File "/home/chenjia/mujoco-py/mujoco_py/mjviewer.py", line 180, in render_inner_loop
    frame = self._read_pixels_as_in_window()
  File "/home/chenjia/mujoco-py/mujoco_py/mjviewer.py", line 218, in _read_pixels_as_in_window
    self.sim.render(resolution[0], resolution[1])
  File "mujoco_py/mjsim.pyx", line 149, in mujoco_py.cymj.MjSim.render
  File "mujoco_py/mjsim.pyx", line 156, in mujoco_py.cymj.MjSim.render
  File "mujoco_py/mjrendercontext.pyx", line 148, in mujoco_py.cymj.MjRenderContext.render
  File "mujoco_py/opengl_context.pyx", line 140, in mujoco_py.cymj.OffscreenOpenGLContext.set_buffer_size
RuntimeError: Failed to set buffer size

**Comment by hhn1n15** [comment]
Hi,

Not related to your question but can I ask how did you train the environment FetchReach-v1 by the baselines code?

Regards,
Hai.
