### ISSUE TITLE
deepq training breaks on loops

### ISSUE THREAD

**Issue by jeremyf21** [openai/baselines#426]
Hi,

I am using deepq to train a custom agent. I am able to train my agent successfully. I am now attempting to do hyper parameter search (i.e. change learning rate, etc.)

When I loop through the code once, everything executes properly, model saves, etc. On the second iteration of the loop, I run in to the following error:

```
Traceback (most recent call last):
  File "train_blindfind_multi.py", line 46, in <module>
    main(lr, exp_frac)
  File "train_blindfind_multi.py", line 28, in main
    callback=None
  File "/home/jeremy/catkin_ws/src/algorithms/baselines/baselines/deepq/simple.py", line 189, in learn
    param_noise=param_noise
  File "/home/jeremy/catkin_ws/src/algorithms/baselines/baselines/deepq/build_graph.py", line 376, in build_train
    act_f = build_act(make_obs_ph, q_func, num_actions, scope=scope, reuse=reuse)
  File "/home/jeremy/catkin_ws/src/algorithms/baselines/baselines/deepq/build_graph.py", line 181, in build_act
    eps = tf.get_variable("eps", (), initializer=tf.constant_initializer(0))
  File "/home/jeremy/.local/share/virtualenvs/algorithms-YDeT6CT5/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1203, in get_variable
    constraint=constraint)
  File "/home/jeremy/.local/share/virtualenvs/algorithms-YDeT6CT5/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1092, in get_variable
    constraint=constraint)
  File "/home/jeremy/.local/share/virtualenvs/algorithms-YDeT6CT5/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 425, in get_variable
    constraint=constraint)
  File "/home/jeremy/.local/share/virtualenvs/algorithms-YDeT6CT5/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 394, in _true_getter
    use_resource=use_resource, constraint=constraint)
  File "/home/jeremy/.local/share/virtualenvs/algorithms-YDeT6CT5/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 742, in _get_single_variable
    name, "".join(traceback.format_list(tb))))
ValueError: Variable deepq/eps already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "/home/jeremy/catkin_ws/src/algorithms/baselines/baselines/deepq/build_graph.py", line 181, in build_act
    eps = tf.get_variable("eps", (), initializer=tf.constant_initializer(0))
  File "/home/jeremy/catkin_ws/src/algorithms/baselines/baselines/deepq/build_graph.py", line 376, in build_train
    act_f = build_act(make_obs_ph, q_func, num_actions, scope=scope, reuse=reuse)
  File "/home/jeremy/catkin_ws/src/algorithms/baselines/baselines/deepq/simple.py", line 189, in learn
    param_noise=param_noise
```

The code for training the agent is the following:

```
def main(lr, exp_frac):
    cwd = Path(os.getcwd())
    env = bf.BlindFindMulti()
    model = deepq.models.mlp([64])
    timestr = time.strftime("%Y%m%d-%H%M%S")
    model_path = "models/model_multi_"+timestr+".pkl"
    env.model_path = cwd / model_path
    act = deepq.learn(
        env,
        q_func=model,
        lr=lr,
        max_timesteps=200,
        buffer_size=200,
        exploration_fraction=exp_frac,
        exploration_final_eps=0.02,
        print_freq=1,
        callback=None
    )

    timestr = time.strftime("%Y%m%d-%H%M%S")
    print("Saving best model...")
    print("model path :", model_path)
    print("learning rate: ", lr)
    print("exploration fraction :", exp_frac)
    print(" ====================================================== ")
    act.save(env.model_path)


if __name__ == '__main__':
    with tf.Graph().as_default():

        exp_frac = 0.1
        for lr in [1e-2, 1e-3]:
            main(lr, exp_frac)

```

I suspect that this is a misuse of tensorflow, but can't seem to get around it.

**Comment by andytwigg** [comment]
Try moving
`with tf.Graph().as_default():`
to within main()

**Comment by jeremyf21** [comment]
That worked, thanks!

**Comment by ArniDagur** [comment]
Putting the following function in a loop (with different environments):
```python
def deepq_learn(env):
    with tf.Graph().as_default():
        deepq.learn(env,
                    network='mlp',
                    lr=1e-3,
                    total_timesteps=20,
                    buffer_size=50000,
                    exploration_fraction=0.2,
                    exploration_final_eps=0.01,
                    print_freq=10)
```
results in the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 303, in __init__
    fetch, allow_tensor=True, allow_operation=True))
  File "/usr/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3796, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/usr/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3880, in _as_graph_element_locked
    raise ValueError("Operation %s is not an element of this graph." % obj)
ValueError: Operation name: "init"
op: "NoOp"
input: "^deepq/eps/Assign"
input: "^deepq/deepq/q_func/state_value/fully_connected_1/biases/Adam/Assign"
input: "^deepq/target_q_func/action_value/fully_connected_1/weights/Assign"
input: "^deepq/q_func/mlp_fc0/w/Assign"
input: "^deepq_1/beta2_power/Assign"
input: "^deepq/deepq/q_func/action_value/fully_connected/biases/Adam/Assign"
input: "^deepq/q_func/action_value/fully_connected_1/weights/Assign"
input: "^deepq/deepq/q_func/mlp_fc1/w/Adam/Assign"
input: "^deepq/target_q_func/state_value/fully_connected_1/biases/Assign"
input: "^deepq/target_q_func/mlp_fc1/b/Assign"
input: "^deepq_1/beta1_power/Assign"
input: "^deepq/target_q_func/mlp_fc1/w/Assign"
input: "^deepq/q_func/state_value/fully_connected_1/biases/Assign"
input: "^deepq/q_func/mlp_fc0/b/Assign"
input: "^deepq/target_q_func/state_value/fully_connected/weights/Assign"
input: "^deepq/q_func/mlp_fc1/w/Assign"
input: "^deepq/target_q_func/mlp_fc0/w/Assign"
input: "^deepq/deepq/q_func/mlp_fc0/b/Adam/Assign"
input: "^deepq/deepq/q_func/action_value/fully_connected/biases/Adam_1/Assign"
input: "^deepq/q_func/state_value/fully_connected/weights/Assign"
input: "^deepq/target_q_func/state_value/fully_connected/biases/Assign"
input: "^deepq/target_q_func/action_value/fully_connected/biases/Assign"
input: "^deepq/deepq/q_func/action_value/fully_connected/weights/Adam_1/Assign"
input: "^deepq/deepq/q_func/action_value/fully_connected_1/weights/Adam_1/Assign"
input: "^deepq/target_q_func/action_value/fully_connected/weights/Assign"
input: "^deepq/deepq/q_func/mlp_fc1/b/Adam/Assign"
input: "^deepq/deepq/q_func/mlp_fc0/w/Adam_1/Assign"
input: "^deepq/deepq/q_func/action_value/fully_connected_1/biases/Adam/Assign"
input: "^deepq/q_func/action_value/fully_connected_1/biases/Assign"
input: "^deepq/q_func/state_value/fully_connected/biases/Assign"
input: "^deepq/deepq/q_func/state_value/fully_connected/biases/Adam/Assign"
input: "^deepq/deepq/q_func/state_value/fully_connected_1/weights/Adam_1/Assign"
input: "^deepq/deepq/q_func/action_value/fully_connected_1/biases/Adam_1/Assign"
input: "^deepq/deepq/q_func/mlp_fc1/b/Adam_1/Assign"
input: "^deepq/q_func/action_value/fully_connected/weights/Assign"
input: "^deepq/deepq/q_func/state_value/fully_connected_1/biases/Adam_1/Assign"
input: "^deepq/q_func/mlp_fc1/b/Assign"
input: "^deepq/q_func/action_value/fully_connected/biases/Assign"
input: "^deepq/deepq/q_func/state_value/fully_connected/weights/Adam/Assign"
input: "^deepq/target_q_func/mlp_fc0/b/Assign"
input: "^deepq/deepq/q_func/state_value/fully_connected/weights/Adam_1/Assign"
input: "^deepq/deepq/q_func/mlp_fc0/b/Adam_1/Assign"
input: "^deepq/deepq/q_func/action_value/fully_connected/weights/Adam/Assign"
input: "^deepq/deepq/q_func/state_value/fully_connected/biases/Adam_1/Assign"
input: "^deepq/deepq/q_func/mlp_fc1/w/Adam_1/Assign"
input: "^deepq/deepq/q_func/action_value/fully_connected_1/weights/Adam/Assign"
input: "^deepq/deepq/q_func/mlp_fc0/w/Adam/Assign"
input: "^deepq/target_q_func/action_value/fully_connected_1/biases/Assign"
input: "^deepq/target_q_func/state_value/fully_connected_1/weights/Assign"
input: "^deepq/deepq/q_func/state_value/fully_connected_1/weights/Adam/Assign"
input: "^deepq/q_func/state_value/fully_connected_1/weights/Assign"
 is not an element of this graph.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 34, in <module>
    main()
  File "main.py", line 30, in main
    agent(env)
  File "/home/arni/OpenSource/TaskTheory/tasktheory/agents.py", line 18, in deepq_learn
    print_freq=10)
  File "/usr/lib/python3.7/site-packages/baselines-0.1.5-py3.7.egg/baselines/deepq/deepq.py", line 237, in learn
    U.initialize()
  File "/usr/lib/python3.7/site-packages/baselines-0.1.5-py3.7.egg/baselines/common/tf_util.py", line 90, in initialize
    get_session().run(tf.variables_initializer(new_variables))
  File "/usr/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/usr/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1158, in _run
    self._graph, fetches, feed_dict_tensor, feed_handles=feed_handles)
  File "/usr/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 474, in __init__
    self._fetch_mapper = _FetchMapper.for_fetch(fetches)
  File "/usr/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 274, in for_fetch
    return _ElementFetchMapper(fetches, contraction_fn)
  File "/usr/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 310, in __init__
    'Tensor. (%s)' % (fetch, str(e)))
ValueError: Fetch argument <tf.Operation 'init' type=NoOp> cannot be interpreted as a Tensor. (Operation name: "init"
op: "NoOp"
input: "^deepq/eps/Assign"
input: "^deepq/deepq/q_func/state_value/fully_connected_1/biases/Adam/Assign"
input: "^deepq/target_q_func/action_value/fully_connected_1/weights/Assign"
input: "^deepq/q_func/mlp_fc0/w/Assign"
input: "^deepq_1/beta2_power/Assign"
input: "^deepq/deepq/q_func/action_value/fully_connected/biases/Adam/Assign"
input: "^deepq/q_func/action_value/fully_connected_1/weights/Assign"
input: "^deepq/deepq/q_func/mlp_fc1/w/Adam/Assign"
input: "^deepq/target_q_func/state_value/fully_connected_1/biases/Assign"
input: "^deepq/target_q_func/mlp_fc1/b/Assign"
input: "^deepq_1/beta1_power/Assign"
input: "^deepq/target_q_func/mlp_fc1/w/Assign"
input: "^deepq/q_func/state_value/fully_connected_1/biases/Assign"
input: "^deepq/q_func/mlp_fc0/b/Assign"
input: "^deepq/target_q_func/state_value/fully_connected/weights/Assign"
input: "^deepq/q_func/mlp_fc1/w/Assign"
input: "^deepq/target_q_func/mlp_fc0/w/Assign"
input: "^deepq/deepq/q_func/mlp_fc0/b/Adam/Assign"
input: "^deepq/deepq/q_func/action_value/fully_connected/biases/Adam_1/Assign"
input: "^deepq/q_func/state_value/fully_connected/weights/Assign"
input: "^deepq/target_q_func/state_value/fully_connected/biases/Assign"
input: "^deepq/target_q_func/action_value/fully_connected/biases/Assign"
input: "^deepq/deepq/q_func/action_value/fully_connected/weights/Adam_1/Assign"
input: "^deepq/deepq/q_func/action_value/fully_connected_1/weights/Adam_1/Assign"
input: "^deepq/target_q_func/action_value/fully_connected/weights/Assign"
input: "^deepq/deepq/q_func/mlp_fc1/b/Adam/Assign"
input: "^deepq/deepq/q_func/mlp_fc0/w/Adam_1/Assign"
input: "^deepq/deepq/q_func/action_value/fully_connected_1/biases/Adam/Assign"
input: "^deepq/q_func/action_value/fully_connected_1/biases/Assign"
input: "^deepq/q_func/state_value/fully_connected/biases/Assign"
input: "^deepq/deepq/q_func/state_value/fully_connected/biases/Adam/Assign"
input: "^deepq/deepq/q_func/state_value/fully_connected_1/weights/Adam_1/Assign"
input: "^deepq/deepq/q_func/action_value/fully_connected_1/biases/Adam_1/Assign"
input: "^deepq/deepq/q_func/mlp_fc1/b/Adam_1/Assign"
input: "^deepq/q_func/action_value/fully_connected/weights/Assign"
input: "^deepq/deepq/q_func/state_value/fully_connected_1/biases/Adam_1/Assign"
input: "^deepq/q_func/mlp_fc1/b/Assign"
input: "^deepq/q_func/action_value/fully_connected/biases/Assign"
input: "^deepq/deepq/q_func/state_value/fully_connected/weights/Adam/Assign"
input: "^deepq/target_q_func/mlp_fc0/b/Assign"
input: "^deepq/deepq/q_func/state_value/fully_connected/weights/Adam_1/Assign"
input: "^deepq/deepq/q_func/mlp_fc0/b/Adam_1/Assign"
input: "^deepq/deepq/q_func/action_value/fully_connected/weights/Adam/Assign"
input: "^deepq/deepq/q_func/state_value/fully_connected/biases/Adam_1/Assign"
input: "^deepq/deepq/q_func/mlp_fc1/w/Adam_1/Assign"
input: "^deepq/deepq/q_func/action_value/fully_connected_1/weights/Adam/Assign"
input: "^deepq/deepq/q_func/mlp_fc0/w/Adam/Assign"
input: "^deepq/target_q_func/action_value/fully_connected_1/biases/Assign"
input: "^deepq/target_q_func/state_value/fully_connected_1/weights/Assign"
input: "^deepq/deepq/q_func/state_value/fully_connected_1/weights/Adam/Assign"
input: "^deepq/q_func/state_value/fully_connected_1/weights/Assign"
 is not an element of this graph.)
```
