### ISSUE TITLE
Missing module

### ISSUE THREAD

**Issue by oeclint** [openai/baselines#429]
I get the following error:

```
Traceback (most recent call last):
  File "acktr-agent.py", line 10, in <module>
    from baselines.common.vec_env.subproc_vec_env import SubprocVecEnv
  File "/Users/clin733/Documents/Scripts/baselines/baselines/common/vec_env/subproc_vec_env.py", line 4, in <module>
    from baselines.common.tile_images import tile_images
ModuleNotFoundError: No module named 'baselines.common.tile_images'
```
I check the repo and it seems like tile_images does not exist.

Thank you.

**Comment by uidilr** [comment]
I think it will be fixed in the PR: #427

**Comment by pzhokhov** [comment]
Correct, and the PR is merged, so should be working now.

**Comment by oeclint** [comment]
Thanks guys!
