### ISSUE TITLE
Not able to run pre-trained model

### ISSUE THREAD

**Issue by yuanzhanghu** [openai/baselines#43]
Both python2 and python3 were not working: 
yhu@yhu-Aspire-M3920:~$ python -m baselines.deepq.experiments.atari.enjoy --model-dir /tmp/models/model-atari-duel-pong-1 --env Pong --dueling
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 102, in _get_module_details
    loader = get_loader(mod_name)
  File "/usr/lib/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "/usr/lib/python2.7/pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "/usr/lib/python2.7/pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "/home/yhu/.local/lib/python2.7/site-packages/baselines/deepq/__init__.py", line 4, in <module>
    from baselines.deepq.simple import learn, load  # noqa
  File "/home/yhu/.local/lib/python2.7/site-packages/baselines/deepq/simple.py", line 10, in <module>
    from baselines import logger
  File "/home/yhu/.local/lib/python2.7/site-packages/baselines/logger.py", line 139
    def log(*args, level=INFO):
                       ^
SyntaxError: invalid syntax
yhu@yhu-Aspire-M3920:~$ python3 -m baselines.deepq.experiments.atari.enjoy --model-dir /tmp/models/model-atari-duel-pong-1 --env Pong --dueling
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/yhu/.local/lib/python3.5/site-packages/baselines/deepq/experiments/atari/enjoy.py", line 15, in <module>
    from baselines.common.atari_wrappers_deprecated import wrap_dqn
  File "/home/yhu/.local/lib/python3.5/site-packages/baselines/common/atari_wrappers_deprecated.py", line 1, in <module>
    import cv2
ImportError: No module named 'cv2'
yhu@yhu-Aspire-M3920:~$

**Comment by abhibhav14** [comment]
Like the error message clearly points out, you need opencv.
Run pip install opencv-python and it should work

**Comment by yuanzhanghu** [comment]
Thanks.  I was thinking that only opencv3 can be installed in python3. 
It worked eventually,  after installing several dependencies: 
sudo apt install cmake; 
sudo pip3 install gym[atari]
sudo pip3 install opencv-python
