### ISSUE TITLE
Error using baselines.results_plotter

### ISSUE THREAD

**Issue by DamienLancry** [openai/baselines#521]
Dear OpenAI and Community,

I am trying to figure out how to use the results_plotter function.
I have run a simple test with the atari environment Pong by running
```
python -m baselines.run --alg=a2c --env=PongNoFrameskip-v4 --num-timesteps=2e7 --save_path=~/models/pong_20M_ppo2
```
and then I ran
```
python -m baselines.results_plotter --dirs=/tmp/openai-2018-08-16-18-14-01-752470
```
And it works perfectly.
But then I tried:
```
python -m baselines.run --alg=ppo2 --env=HalfCheetah-v2 --num_env=8 --save_path=~/models/HC_1M_ppo2
```
then:
```
python -m baselines.results_plotter --dirs=/tmp/openai-2018-08-18-17-32-10-748103
```
And I get the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/homes/drl17/Documents/Project/baselines/results_plotter.py", line 87, in <module>
    main()
  File "/homes/drl17/Documents/Project/baselines/results_plotter.py", line 83, in main
    plot_results(args.dirs, args.num_timesteps, args.xaxis, args.task_name)
  File "/homes/drl17/Documents/Project/baselines/results_plotter.py", line 61, in plot_results
    ts = load_results(dir)
  File "/homes/drl17/Documents/Project/baselines/bench/monitor.py", line 119, in load_results
    df = pandas.read_csv(fh, index_col=None)
  File "/homes/drl17/Documents/Project/Torcs_Project/env3/lib/python3.5/site-packages/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/homes/drl17/Documents/Project/Torcs_Project/env3/lib/python3.5/site-packages/pandas/io/parsers.py", line 446, in _read
    data = parser.read(nrows)
  File "/homes/drl17/Documents/Project/Torcs_Project/env3/lib/python3.5/site-packages/pandas/io/parsers.py", line 1036, in read
    ret = self._engine.read(nrows)
  File "/homes/drl17/Documents/Project/Torcs_Project/env3/lib/python3.5/site-packages/pandas/io/parsers.py", line 1848, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 876, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 891, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 945, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 932, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2112, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 3 fields in line 7, saw 5
```
At first i thought it was because i used the argument num_env=8 but then i realized that atari uses the num_env= multiprocessing.cpu_count() by default.
So any idea where this is coming from?

Cheers!

**Comment by DamienLancry** [comment]
I am really struggling with how to use these functions, but they would be really useful ...
Does anybody know how to use them properly?

**Comment by erincmer** [comment]
This happens to me when I log results into same folder. just check if many .monitor files are in the same folder

**Comment by DamienLancry** [comment]
Hi thanks for your answer,
Unfortunately I dont think my problem is related to that because I let the default log directories , that is tmp/openai-<date+hour> and as a consequence there is always only one log results per directory. :(

**Comment by DamienLancry** [comment]
Could be because we need at least a hundred episodes per agent and the training only lasts 1M timesteps for all agents if my understanding is correct.

**Comment by erincmer** [comment]
100 episode can be changed in result_plotter you can set it to even 1. HalfCheetah is long episode environment try Hopper.  if there are less episodes it gives negative dimensions are not allowed error, your error is from .monitor files it can not parse them since you may use same monitor file more than once(if 8 env all write to same .monitor.csv) and it overrides , check number of rows in .monitor.csv file it should be 3 rows you have 5 hence it can not parse.

**Comment by DamienLancry** [comment]
yes it is the monitor.csv that is very messy. I think it s not good with multiprocessing on mujoco environments which is a pity. But maybe it s just me not doing it right.

**Comment by GbengaOdesanmi** [comment]
Please am having similar problem, where to get monitor.csv file please 

python -m baselines.results_plotter --dirs=/tmp/openai-2018-11-30-16-53-40-674939
Traceback (most recent call last):
  File "/home/gbenga/Downloads/abiona1008/envs/tensorflow/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/gbenga/Downloads/abiona1008/envs/tensorflow/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/gbenga/baselines/baselines/results_plotter.py", line 95, in <module>
    main()
  File "/home/gbenga/baselines/baselines/results_plotter.py", line 91, in main
    plot_results(args.dirs, args.num_timesteps, args.xaxis, args.yaxis, args.task_name)
  File "/home/gbenga/baselines/baselines/results_plotter.py", line 68, in plot_results
    ts = load_results(dir)
  File "/home/gbenga/baselines/baselines/bench/monitor.py", line 134, in load_results
    raise LoadMonitorResultsError("no monitor files of the form *%s found in %s" % (Monitor.EXT, dir))
baselines.bench.monitor.LoadMonitorResultsError: no monitor files of the form *monitor.csv found in /tmp/openai-2018-11-30-16-53-40-674939
