### ISSUE TITLE
Problem using PLAY when LSTM network is selected

### ISSUE THREAD

**Issue by R1ckF** [openai/baselines#576]
Hi all,

I think i discovered a bug. When trying to play using an LSTM network I get a placeholder error:

```
Traceback (most recent call last):
  File "/home/feith/miniconda3/envs/mujoco/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call
    return fn(*args)
  File "/home/feith/miniconda3/envs/mujoco/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/feith/miniconda3/envs/mujoco/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'a2c_model/pi/Placeholder_3' with dtype float and shape [1,256]
	 [[Node: a2c_model/pi/Placeholder_3 = Placeholder[dtype=DT_FLOAT, shape=[1,256], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/feith/miniconda3/envs/mujoco/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/feith/miniconda3/envs/mujoco/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/feith/Gits/baselines/baselines/run.py", line 256, in <module>
    main()
  File "/home/feith/Gits/baselines/baselines/run.py", line 244, in main
    actions = model.step(obs)[0]
  File "/home/feith/Gits/baselines/baselines/common/policies.py", line 89, in step
    a, v, state, neglogp = self._evaluate([self.action, self.vf, self.state, self.neglogp], observation, **extra_feed)
  File "/home/feith/Gits/baselines/baselines/common/policies.py", line 71, in _evaluate
    return sess.run(variables, feed_dict)
  File "/home/feith/miniconda3/envs/mujoco/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/home/feith/miniconda3/envs/mujoco/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/feith/miniconda3/envs/mujoco/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/home/feith/miniconda3/envs/mujoco/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'a2c_model/pi/Placeholder_3' with dtype float and shape [1,256]
	 [[Node: a2c_model/pi/Placeholder_3 = Placeholder[dtype=DT_FLOAT, shape=[1,256], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'a2c_model/pi/Placeholder_3', defined at:
  File "/home/feith/miniconda3/envs/mujoco/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/feith/miniconda3/envs/mujoco/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/feith/Gits/baselines/baselines/run.py", line 256, in <module>
    main()
  File "/home/feith/Gits/baselines/baselines/run.py", line 230, in main
    model, _ = train(args, extra_args)
  File "/home/feith/Gits/baselines/baselines/run.py", line 76, in train
    **alg_kwargs
  File "/home/feith/Gits/baselines/baselines/a2c/a2c.py", line 157, in learn
    max_grad_norm=max_grad_norm, lr=lr, alpha=alpha, epsilon=epsilon, total_timesteps=total_timesteps, lrschedule=lrschedule)
  File "/home/feith/Gits/baselines/baselines/a2c/a2c.py", line 30, in __init__
    step_model = policy(nenvs, 1, sess)
  File "/home/feith/Gits/baselines/baselines/common/policies.py", line 144, in policy_fn
    policy_latent, recurrent_tensors = policy_network(encoded_x, nenv)
  File "/home/feith/Gits/baselines/baselines/common/models.py", line 105, in network_fn
    S = tf.placeholder(tf.float32, [nenv, 2*nlstm]) #states
  File "/home/feith/miniconda3/envs/mujoco/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1735, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "/home/feith/miniconda3/envs/mujoco/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 4925, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/home/feith/miniconda3/envs/mujoco/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/feith/miniconda3/envs/mujoco/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/home/feith/miniconda3/envs/mujoco/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/home/feith/miniconda3/envs/mujoco/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'a2c_model/pi/Placeholder_3' with dtype float and shape [1,256]
	 [[Node: a2c_model/pi/Placeholder_3 = Placeholder[dtype=DT_FLOAT, shape=[1,256], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

```
During training the model.step function also feeds placeholders. 
I have altered the code slightly and now it works. I just filled the placeholders with zeros as a print statement of the first state during training also consisted of only zeroes. During the next loop the previous states are used.

```
if args.play:
        logger.log("Running trained model")
        env = build_env(args)
        obs = env.reset()
        nlstm=128 #default change if different
        play_S = np.zeros((args.num_env,2*nlstm))
        play_M = np.zeros((1))
        while True:
            actions,_,play_S,_ = model.step(obs,S=play_S, M=play_M)
            obs, _, done, _ = env.step(actions)
            env.render()
            done = done.any() if isinstance(done, np.ndarray) else done
            if done:
                obs = env.reset()
```

Has anybody else encoutered this error? What solutions did you use?
Thx!

**Comment by R1ckF** [comment]
Just tried to train ppo2 using LSTM and the same error popped up. Are they related? 
This time changing "value_network="copy"" to "None" enabled me to train again. But this does not seem like a real solution. 
Any help is appreciated :)

**Comment by pzhokhov** [comment]
https://github.com/openai/baselines/issues/579

**Comment by pzhokhov** [comment]
ah yes, you are right, play section does need to be modified too. Care to make a PR? Otherwise, I'll fix it shortly.

**Comment by R1ckF** [comment]
No problem, I created a PR that solves the issue.
