### ISSUE TITLE
Error in using ppo2 to train HalfCheetah-v2

### ISSUE THREAD

**Issue by huangjiancong1** [openai/baselines#587]
Command:
`python -m baselines.run --alg=ppo2 --env=HalfCheetah-v2 --network=mlp --num_timesteps=2e7 --ent_coef=0.1 --num_hidden=32 --num_layers=3 --value_network=copy --save_path=baselines/baselines/ppo2/halfcheetah/models_2e7`

Error output:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/huang/baselines/baselines/run.py", line 234, in <module>
    main()
  File "/home/huang/baselines/baselines/run.py", line 211, in main
    model, env = train(args, extra_args)
  File "/home/huang/baselines/baselines/run.py", line 79, in train
    **alg_kwargs
  File "/home/huang/baselines/baselines/ppo2/ppo2.py", line 245, in learn
    obs, returns, masks, actions, values, neglogpacs, states, epinfos = runner.run() #pylint: disable=E0632
  File "/home/huang/baselines/baselines/ppo2/ppo2.py", line 110, in run
    self.obs[:], rewards, self.dones, infos = self.env.step(actions)
  File "/home/huang/baselines/baselines/common/vec_env/__init__.py", line 98, in step
    return self.step_wait()
  File "/home/huang/baselines/baselines/common/vec_env/vec_normalize.py", line 23, in step_wait
    obs, rews, news, infos = self.venv.step_wait()
  File "/home/huang/baselines/baselines/common/vec_env/dummy_vec_env.py", line 40, in step_wait
    obs, self.buf_rews[e], self.buf_dones[e], self.buf_infos[e] = self.envs[e].step(action)
  File "/home/huang/baselines/baselines/bench/monitor.py", line 60, in step
    ob, rew, done, info = self.env.step(action)
  File "/home/huang/gym/gym/wrappers/time_limit.py", line 31, in step
    observation, reward, done, info = self.env.step(action)
  File "/home/huang/gym/gym/envs/mujoco/half_cheetah.py", line 12, in step
    self.do_simulation(action, self.frame_skip)
  File "/home/huang/gym/gym/envs/mujoco/mujoco_env.py", line 106, in do_simulation
    self.sim.step()
  File "mujoco_py/mjsim.pyx", line 119, in mujoco_py.cymj.MjSim.step
  File "mujoco_py/cymj.pyx", line 115, in mujoco_py.cymj.wrap_mujoco_warning.__exit__
  File "mujoco_py/cymj.pyx", line 75, in mujoco_py.cymj.c_warning_callback
  File "/home/huang/venv/lib/python3.6/site-packages/mujoco_py/builder.py", line 331, in user_warning_raise_exception
    raise MujocoException('Got MuJoCo Warning: {}'.format(warn))
mujoco_py.builder.MujocoException: Got MuJoCo Warning: Unknown warning type Time = 35.7000.

```

Before it , i choice `--num_timesteps=100000`, It can finish trainning and play.
But, i use `--num_timesteps=2e7` now, It can train at the beginning, and Trackback nearly after 1 hours.

**Comment by pzhokhov** [comment]
Hi @huangjiancong1 . I am trying to reproduce... Is there any setting in which you have seen it appear faster? Also, could you provide your mujoco and mujoco_py version? 
Given the stacktrace, it looks like the error is somewhere deep in the guts of mujoco... so as a temporary workaround you can try bullet (`pip install pybullet`, and then `use --env HalfCheetahBulletEnv-v0` with baselines.run (the rest stays the same).

**Comment by huangjiancong1** [comment]
Mujoco version: pro150 for Linux
Mujoco-py version: ` pip3 install -U 'mujoco-py<1.50.2,>=1.50.1'
` the package from [mujoco-py](https://github.com/openai/mujoco-py) recently.

1、I setting the `--num_times tep=10000`, it will train faster and play with the setting`--num_timestep=0 ` .And there is some question that when i try to train `num_timestep`more than 4500000, it will output error as i illustrated above. 
2、It can train with ppo2, and some gym/env just like Humanoid-v2 played not good(I think it is some think wrong about mujoco/camera. In mujoco, the lens will zoom out and the model will disappear into the lens.)

**Comment by huangjiancong1** [comment]
Hi,@pzhokhov, I find out that this question is about GPU capacity，the error output in the 4G GPU but finished training in 12G GPU with `num_timestep=2e7`. So, So, what kind of configuration is suitable for training?
