### ISSUE TITLE
RuntimeError: received 0 items of ancdata with custom gym

### ISSUE THREAD

**Issue by Atcold** [openai/baselines#619]
I'm getting a `RuntimeError` when I try to run several custom gyms in parallel.

```python
Traceback (most recent call last):
  File "/misc/vlgscratch4/LecunGroup/atcold/anaconda3/envs/OpenAI/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/misc/vlgscratch4/LecunGroup/atcold/anaconda3/envs/OpenAI/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/atcold/Work/GitHub/OpenAI-RL-baselines/baselines/run.py", line 270, in <module>
    main()
  File "/home/atcold/Work/GitHub/OpenAI-RL-baselines/baselines/run.py", line 244, in main
    model, env = train(args, extra_args)
  File "/home/atcold/Work/GitHub/OpenAI-RL-baselines/baselines/run.py", line 88, in train
    **alg_kwargs
  File "/home/atcold/Work/GitHub/OpenAI-RL-baselines/baselines/ppo2/ppo2.py", line 329, in learn
    obs, returns, masks, actions, values, neglogpacs, states, epinfos = runner.run() #pylint: disable=E0632
  File "/home/atcold/Work/GitHub/OpenAI-RL-baselines/baselines/ppo2/ppo2.py", line 178, in run
    self.obs[:], rewards, self.dones, infos = self.env.step(actions)
  File "/home/atcold/Work/GitHub/OpenAI-RL-baselines/baselines/common/vec_env/__init__.py", line 100, in step
    return self.step_wait()
  File "/home/atcold/Work/GitHub/OpenAI-RL-baselines/baselines/common/vec_env/vec_normalize.py", line 23, in step_wait
    obs, rews, news, infos = self.venv.step_wait()
  File "/home/atcold/Work/GitHub/OpenAI-RL-baselines/baselines/common/vec_env/subproc_vec_env.py", line 70, in step_wait
    results = [remote.recv() for remote in self.remotes]
  File "/home/atcold/Work/GitHub/OpenAI-RL-baselines/baselines/common/vec_env/subproc_vec_env.py", line 70, in <listcomp>
    results = [remote.recv() for remote in self.remotes]
  File "/misc/vlgscratch4/LecunGroup/atcold/anaconda3/envs/OpenAI/lib/python3.6/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
  File "/misc/vlgscratch4/LecunGroup/atcold/anaconda3/envs/OpenAI/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 151, in rebuild_storage_fd
    fd = df.detach()
  File "/misc/vlgscratch4/LecunGroup/atcold/anaconda3/envs/OpenAI/lib/python3.6/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/misc/vlgscratch4/LecunGroup/atcold/anaconda3/envs/OpenAI/lib/python3.6/multiprocessing/reduction.py", line 182, in recv_handle
    return recvfds(s, 1)[0]
  File "/misc/vlgscratch4/LecunGroup/atcold/anaconda3/envs/OpenAI/lib/python3.6/multiprocessing/reduction.py", line 161, in recvfds
    len(ancdata))
RuntimeError: received 0 items of ancdata
```

No clue about how to debug this.
Do I need to add any special functionality to my gym to support parallel execution?

**Comment by pzhokhov** [comment]
Hi @Atcold! SubprocVecEnv often conceals the right error message, but to my experience, relatively rarely causes the errors itself; so the first thing I'd try is to using DummyVecEnv instead of SubprocVecEnv (if you are using baselines.run to start things, that would mean modify baselines/baselines/common/cmd_util.py, make_vec_env method - replace SubprocVecEnv with DummyVecEnv there). If DummyVecEnv version works with no errors, then there is indeed some conflict between your custom environments running in parallel... debugging that could be a bit painful, what I would do is try to catch all exceptions in the SubprocVecEnv worker and send them to the master process through the pipe; and then read those. Let me know if that helps; I'd be happy to elaborate on any of the points above.

**Comment by Atcold** [comment]
I was previously using the `DummyVecEnv` without any issue.
The same holds for `SubprocVecEnv` when no workers are used.
It's the first time I'm playing with threads. I'll try to catch the exception in the worker and send it back, if I figure out how to do so. I'll post here my findings. Thanks for the support!

**Comment by Atcold** [comment]
So... I think `VecEnv` keeps stepping, and therefore `SubprocVecEnv.step_async(action)` keeps been called, which in turn issues a `remote.send(('step', action))` even when one remote's gym has exhausted the episode. My gym has/had an undefined behaviour for stepping after episode completion.
What is the assumption here, for stepping on a `done`-ed environment?

**Comment by Atcold** [comment]
Alright. Made some progress.
`ulimit -n` returns `1024`. Setting `ulimit -n 2048` made the script work for longer, but it died afterwards.
So, I'm pretty sure I'm hitting "some" limit due to some missing deallocation of resources. I have now to figure out who's doing this nasty thing.

**Comment by Atcold** [comment]
Finally debugged this crap.
It's actually quite embarrassing typing here what was the cause... but I'll do it for sake of rigour.

My gym `step(action)` function was returning:

 - `observation`: a NumPy multidimensional array;
 - `reward`: a scalar;
 - `done`: a boolean;
 - `info`: the whole agent (for debugging purposes).

The thing that I didn't take in account is that with multiple processes the agent has to be serialised and sent through a pipe. My agent contains a crap ton of stuff, pandas tables, pygame cached font, and more shit.

Sending `str(agent)` instead (which is telling my *who* the current agent is) fixes the problem.

Now I have a new bug
```python
self.ret = self.ret * self.gamma + rews
ValueError: operands could not be broadcast together with shapes (12,) (2,)
```
but this is a new adventure by its own, so I'm closing this issue.
Thank you for your interest. I hope I've entertained you ;)
