### ISSUE TITLE
ImportError: cannot import name 'weakref'

### ISSUE THREAD

**Issue by tigerneil** [openai/baselines#62]
any comment?

```
➜  baselines git:(master) python baselines/pposgd/run_atari.py
Traceback (most recent call last):
  File "baselines/pposgd/run_atari.py", line 54, in <module>
    main()
  File "baselines/pposgd/run_atari.py", line 51, in main
    train('PongNoFrameskip-v4', num_timesteps=40e6, seed=0, num_cpu=8)
  File "baselines/pposgd/run_atari.py", line 18, in train
    from baselines.pposgd import pposgd_simple, cnn_policy
  File "/Users/Tiger/projects/baselines/baselines/pposgd/pposgd_simple.py", line 3, in <module>
    import baselines.common.tf_util as U
  File "/Users/Tiger/projects/baselines/baselines/common/tf_util.py", line 2, in <module>
    import tensorflow as tf  # pylint: ignore-module
  File "/Users/Tiger/anaconda/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Users/Tiger/anaconda/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.python.framework.framework_lib import *
  File "/Users/Tiger/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/framework_lib.py", line 100, in <module>
    from tensorflow.python.framework.subscribe import subscribe
  File "/Users/Tiger/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/subscribe.py", line 26, in <module>
    from tensorflow.python.ops import variables
  File "/Users/Tiger/anaconda/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 26, in <module>
    from tensorflow.python.ops import control_flow_ops
  File "/Users/Tiger/anaconda/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 70, in <module>
    from tensorflow.python.ops import tensor_array_ops
  File "/Users/Tiger/anaconda/lib/python3.5/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 33, in <module>
    from tensorflow.python.util import tf_should_use
  File "/Users/Tiger/anaconda/lib/python3.5/site-packages/tensorflow/python/util/tf_should_use.py", line 28, in <module>
    from backports import weakref  # pylint: disable=g-bad-import-order
ImportError: cannot import name 'weakref'
```

**Comment by tigerneil** [comment]
```
➜  baselines git:(master) python
Python 3.5.3 |Anaconda 4.2.0 (x86_64)| (default, Feb 22 2017, 20:51:01)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import backports
>>> import backports as bp
>>> bp.weakref
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'backports' has no attribute 'weakref'
>>> exit()
➜  baselines git:(master) pip install backports.weakref
Requirement already satisfied: backports.weakref in /Users/Tiger/anaconda/envs/rllab3/lib/python3.5/site-packages
➜  baselines git:(master) pip install -U backports.weakref
Requirement already up-to-date: backports.weakref in /Users/Tiger/anaconda/envs/rllab3/lib/python3.5/site-packages
➜  baselines git:(master)
```

**Comment by AdamStelmaszczyk** [comment]
`-U` flag didn't force reinstall, try `uninstall` and then `install`. Anyway, it looks like a problem in TF, so might be worth checking their issues (or ask if no issue found).

**Comment by pnlawlor** [comment]
I was having the same issue. The following worked for me:

In path/to/python/env/Lib/site-packages/tensorflow/python/util/tf_should_use.py
Change line 28:
`from backports import weakref  # pylint: disable=g-bad-import-order`
to
`import weakref`

**Comment by go361** [comment]
@pnlawlor 
Thanks, your solution is also useful for me!

**Comment by iamhabbeboy** [comment]
Locate the path here for mac user
 `/usr/local/lib/python2.7/site-packages/tensorflow/python/util/tf_should_use.py`
then continue with @pnlawlor solution
