### ISSUE TITLE
ACER Models don't run ... dimension error?

### ISSUE THREAD

**Issue by jjfiv** [openai/baselines#623]
Hi!

I've only really tried Atari environments, so it may work in other circumstances.

There seems to be a bug in the tensorflow-serialized model. If I run something like this: (where start_python merely sets PYTHONPATH). 

```sh
./start_python -m baselines.run --alg=acer --env=BreakoutNoFrameskip-v0 --num_timesteps=1000 --save_path=$PWD/acer1k.model --num_env=1
./start_python -m baselines.run --alg=acer --env=BreakoutNoFrameskip-v0 --num_timesteps=0 --load_path=acer1k --play --num_env=1
```

I get a whole bunch of output from training, but upon testing...

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/jfoley/code/toybox/openai/baselines/baselines/run.py", line 275, in <module>
    main()
  File "/Users/jfoley/code/toybox/openai/baselines/baselines/run.py", line 241, in main
    actions = model.step(obs)[0]
  File "/Users/jfoley/code/toybox/openai/baselines/baselines/common/policies.py", line 89, in step
    a, v, state, neglogp = self._evaluate([self.action, self.vf, self.state, self.neglogp], observation, **extra_feed)
  File "/Users/jfoley/code/toybox/openai/baselines/baselines/common/policies.py", line 64, in _evaluate
    feed_dict = {self.X: adjust_shape(self.X, observation)}
  File "/Users/jfoley/code/toybox/openai/baselines/baselines/common/tf_util.py", line 388, in adjust_shape
    return np.reshape(data, placeholder_shape)
  File "/usr/local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 257, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/usr/local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 52, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 7056 into shape (1,84,84,4)
```

I can hack to avoid the reshape, but this breaks other models, and I don't really know what's going on. I couldn't find any ACER issues in the repo or commit history, but apologies if this was solved recently.

I'm on a cheap Macbook Air if that makes any difference.

**Comment by jjfiv** [comment]
Hi @pzhokhov!

Thanks for the quick response!

We had ruled that out because we thought our env was getting wrapped in the [VecFrameStack](https://github.com/openai/baselines/blob/master/baselines/common/vec_env/vec_frame_stack.py) which we thought was already doing this, but we will debug further. Thanks for the expert look.

Any ETA on that refactor? We'll prioritize this if it's a few months out, but we're happy to wait a few weeks.

Thanks again!
John

**Comment by pzhokhov** [comment]
Hi John!  I'd estimate this refactor as being 3-5 weeks away; but no strict promises :)

**Comment by pzhokhov** [comment]
this should solve the issue: https://github.com/openai/baselines/pull/664

**Comment by jjfiv** [comment]
Looks good to me! Thanks for the help!
