### ISSUE TITLE
load_results method throws Monitor error

### ISSUE THREAD

**Issue by cli0** [openai/baselines#624]
A simple call ` load_results(log_dir)` throws the following error

```
Traceback (most recent call last):
  File "RLBaseline.py", line 59, in <module>
    main()
  File "RLBaseline.py", line 55, in main
    plot_results(dirs=log_dir, num_timesteps=100000, xaxis="timesteps",yaxis='reward', task_name='Learning Curve')
  File "/home/user/Desktop/baselines/baselines/results_plotter.py", line 68, in plot_results
    ts = load_results(dir)
  File "/home/user/Desktop/baselines/baselines/bench/monitor.py", line 134, in load_results
    raise LoadMonitorResultsError("no monitor files of the form *%s found in %s" % (Monitor.EXT, dir))
baselines.bench.monitor.LoadMonitorResultsError: no monitor files of the form *monitor.csv found in /

```

How do I generate/what do I need to do to generate the monitor file as well?

**Comment by pzhokhov** [comment]
monitor files are files generated by the Monitor env wrapper (baselines.bench.monitor.Monitor) that keeps track of the episodes and saves lengths, times and returns (sum of rewards on each step) for each episode. So in order to get such file, wrap your environment with Monitor wrapper - something like:
```
import gym
from baselines.bench.monitor import Monitor
env = gym.make('PongNoFrameskip-v2')
env = Monitor(env, log_dir)
```

**Comment by pzhokhov** [comment]
closing this, please reopen if that does not help
