### ISSUE TITLE
ModuleNotFoundError when running PPO1

### ISSUE THREAD

**Issue by zhangchuheng123** [openai/baselines#719]
Problem:

I followed the instructions to install baselines from github repo, and simply replaced ppo2 by ppo1. 

```
python -m baselines.run --alg=ppo1 --env=Hopper-v2 --network=mlp --num_timesteps=2e7
```

I got following error.

```
$ python -m baselines.run --alg=ppo1 --env=Hopper-v2 --network=mlp --num_timesteps=2e7

/home1/zhangchuheng/miniconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Logging to /tmp/openai-2018-11-16-21-38-25-152557
Logging to /tmp/openai-2018-11-16-21-38-25-254664
env_type: mujoco
Traceback (most recent call last):
  File "/home1/zhangchuheng/projects/baseline/baselines/baselines/run.py", line 146, in get_alg_module
    alg_module = import_module('.'.join(['baselines', alg, submodule]))
  File "/home1/zhangchuheng/miniconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'baselines.ppo1.ppo1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home1/zhangchuheng/miniconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home1/zhangchuheng/miniconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home1/zhangchuheng/projects/baseline/baselines/baselines/run.py", line 224, in <module>
    main()
  File "/home1/zhangchuheng/projects/baseline/baselines/baselines/run.py", line 198, in main
    model, env = train(args, extra_args)
  File "/home1/zhangchuheng/projects/baseline/baselines/baselines/run.py", line 61, in train
    learn = get_learn_function(args.alg)
  File "/home1/zhangchuheng/projects/baseline/baselines/baselines/run.py", line 155, in get_learn_function
    return get_alg_module(alg).learn
  File "/home1/zhangchuheng/projects/baseline/baselines/baselines/run.py", line 149, in get_alg_module
    alg_module = import_module('.'.join(['rl_' + 'algs', alg, submodule]))
  File "/home1/zhangchuheng/miniconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rl_algs'
```

I found that it looks for the submodule ``baselines.ppo1.ppo1`` in ``run.py``. However, there is not a ``ppo1.py`` under the path like other algorithms do.

```
def get_alg_module(alg, submodule=None):
    submodule = submodule or alg
    try:
        # first try to import the alg module from baselines
        alg_module = import_module('.'.join(['baselines', alg, submodule]))
    except ImportError:
        # then from rl_algs
        alg_module = import_module('.'.join(['rl_' + 'algs', alg, submodule]))

    return alg_module
```

**Comment by zhangchuheng123** [comment]
Sorry, I just realized that PPO1 is currently not supported.
