### ISSUE TITLE
undefined symbol

### ISSUE THREAD

**Issue by GbengaOdesanmi** [openai/baselines#742]
Please, I am having this error, kindly help me out on how to solve it, I tried this but not repeating itself.
conda install -y --verbose -c conda-forge opencv==3.4.1 tensorflow==1.8.0

(tensorflow) gbenga@gbenga-Lenovo:~/baselines$ python -m baselines.her.experiment.train --num_cpu 1
Logging to /tmp/openai-2018-11-29-18-55-47-521866
Traceback (most recent call last):
  File "/home/gbenga/Downloads/abiona1008/envs/tensorflow/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/gbenga/Downloads/abiona1008/envs/tensorflow/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/gbenga/baselines/baselines/her/experiment/train.py", line 12, in <module>
    import baselines.her.experiment.config as config
  File "/home/gbenga/baselines/baselines/her/experiment/config.py", line 5, in <module>
    from baselines.her.ddpg import DDPG
  File "/home/gbenga/baselines/baselines/her/ddpg.py", line 4, in <module>
    import tensorflow as tf
  File "/home/gbenga/Downloads/abiona1008/envs/tensorflow/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/gbenga/Downloads/abiona1008/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 59, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/home/gbenga/Downloads/abiona1008/envs/tensorflow/lib/python3.6/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/home/gbenga/Downloads/abiona1008/envs/tensorflow/lib/python3.6/site-packages/google/protobuf/descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: /home/gbenga/Downloads/abiona1008/envs/tensorflow/lib/python3.6/site-packages/google/protobuf/pyext/_message.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNK6google8protobuf10TextFormat17FieldValuePrinter9PrintBoolEb

**Comment by GbengaOdesanmi** [comment]
I have solve this using 
conda install -y --verbose -c conda-forge opencv==3.4.1 tensorflow==1.8.0 but it doesn't work and later install protobof package using 
conda install -c anaconda protobuf

**Comment by pzhokhov** [comment]
Hi @GbengaOdesanmi ! This sounds like a tensorflow issue (rather than baselines issue) to me... 
Does your installation run `python -c "import tensorflow"` command without errors? 
Also, do I understand it correctly that you solved the issue by running
```
conda install -c anaconda protobuf
```
if so, let's close this ; in any case it would be good to forward it to either anaconda or tensorflow community.

**Comment by GbengaOdesanmi** [comment]
Thanks, please how to do that?

**Comment by pzhokhov** [comment]
Not sure I understand what are referring to...
1) How to test if you python environment and tensorflow are working - in the command line type `python -c "import tensorflow"` or in a clean jupyter notebook type in "import tensorflow". That command should finish without errors. 
2) How to forward it to anaconda / tensorflow - file issue on https://github.com/ContinuumIO/anaconda-issues or https://github.com/tensorflow/tensorflow
3) How to close it - click "Close" button :)
