### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by yigemaserwang** [openai/baselines#760]
run "python -m baselines.run --alg=ppo2 --env=Humanoid-v2 --network=mlp --num_timesteps=2e"
show error as next:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/a/Documents/soft/baselines/baselines/run.py", line 11, in <module>
    from baselines.common.cmd_util import common_arg_parser, parse_unknown_args, make_vec_env, make_env
  File "/Users/a/Documents/soft/baselines/baselines/common/cmd_util.py", line 16, in <module>
    from baselines.common.atari_wrappers import make_atari, wrap_deepmind
  File "/Users/a/Documents/soft/baselines/baselines/common/atari_wrappers.py", line 7, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
------------------------------------------------------------------------------
i get run these ok :
(baseline) adeiMac:baselines a$ pip install opencv-python
(baseline) adeiMac:baselines a$ pip install opencv-contrib-python 
(baseline) adeiMac:baselines a$ conda install py-opencv
------------------------------------------------------------------------------
but it still get error ,ModuleNotFoundError: No module named 'cv2'
so, i check run 
(baseline) adeiMac:baselines a$ conda list 
.......
libopencv                 3.4.2                h7c891bd_1  
...
opencv-contrib-python     3.4.4.19                  <pip>
opencv-python             3.4.4.19   
...
py-opencv                 3.4.2            py36h7c891bd_1  

what should i do next?

**Comment by Olimoyo** [comment]
Are you able to import cv2 in your normal python environment?

**Comment by DanielTakeshi** [comment]
It would be best if you could describe the exact steps to reproduce your error. Start with a clean terminal. Make a virtualenv. Show `pip list`, and all the commands you use. Show your PYTHONPATH. Otherwise we'll be forced to almost randomly guess and propose solutions.
