### ISSUE TITLE
Her Result Plot

### ISSUE THREAD

**Issue by GbengaOdesanmi** [openai/baselines#769]
Please am having this error while trying to plot the result. How do I solve it? Thanks

python -m baselines.her.experiment.plot /tmp/openai-2018-12-19-12-21-56-179878/policy_995.pkl 
/home/gbenga/Downloads/abiona1008/envs/tensorflow/lib/python3.6/site-packages/matplotlib/__init__.py:886: MatplotlibDeprecationWarning: 
examples.directory is deprecated; in the future, examples will be found relative to the 'datapath' directory.
  "found relative to the 'datapath' directory.".format(key))

**Comment by pzhokhov** [comment]
Hi @GbengaOdesanmi ! This looks like a warning, not an error... Are the results not plotted after all? Also, check out the new and refactored code for running and plotting HER experiments (has been merged in master recently :))

**Comment by GbengaOdesanmi** [comment]
I can't find any plot after, please help me, where to find the plot, because I cannot find it anywhere. thanks in advance

I also use this method but doesn't work

>> results = pu.load_results('/tmp/openai-2018-12-19-12-21-56-179878')
>>> import matplotlib.pyplot as plt
>>> import numpy as np
>>> r = results[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: list index out of range
>>> r = results[1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: list index out of range
>>> r = results[]
  File "<stdin>", line 1
    r = results[]
                ^
SyntaxError: invalid syntax
>>> r = results
>>> plt.plot(np.cumsum(r.monitor.l), r.monitor.r)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'list' object has no attribute 'monitor'
>>> pu.plot_results(results)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gbenga/baselines/baselines/common/plot_util.py", line 298, in plot_results
    assert len(sk2r) > 0
AssertionError
>>> results = pu.load_results('/tmp/openai-2018-12-19-12-21-56-179878'); print(len(results))
0
>>>
