### ISSUE TITLE
Missing arguments in call to build policy when using ACER with LSTM. 

### ISSUE THREAD

**Issue by ethanwaldie** [openai/baselines#783]
Hi there, 

I have been trying to use the ACER model with an LSTM policy or:

`python -m baselines.run --alg=acer --env=CartPole-v0 --network=lstm`

However I am consistently getting the following error: 

```
Traceback (most recent call last):
  File "/Users/ethanwaldie/anaconda3/envs/malmo_env/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/ethanwaldie/anaconda3/envs/malmo_env/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/ethanwaldie/thesis/baselines/baselines/run.py", line 240, in <module>
    main(sys.argv)
  File "/Users/ethanwaldie/thesis/baselines/baselines/run.py", line 207, in main
    model, env = train(args, extra_args)
  File "/Users/ethanwaldie/thesis/baselines/baselines/run.py", line 81, in train
    **alg_kwargs
  File "/Users/ethanwaldie/thesis/baselines/baselines/acer/acer.py", line 359, in learn
    trust_region=trust_region, alpha=alpha, delta=delta)
  File "/Users/ethanwaldie/thesis/baselines/baselines/acer/acer.py", line 78, in __init__
    step_model = policy(observ_placeholder=step_ob_placeholder, sess=sess)
  File "/Users/ethanwaldie/thesis/baselines/baselines/common/policies.py", line 148, in policy_fn
    nenv = nbatch // nsteps
TypeError: unsupported operand type(s) for //: 'NoneType' and 'NoneType'
```

When following the stacktrace I have found the following lines to be of issue, Inside the model object in acer.py the policy builder is called with insufficient arguments for a recurrent policy. 

lines 78 and 79 in acer.py:

``` 
with tf.variable_scope('acer_model', reuse=tf.AUTO_REUSE):
            step_model = policy(observ_placeholder=step_ob_placeholder, sess=sess)
            train_model = policy(observ_placeholder=train_ob_placeholder, sess=sess)
```

This causes the code to break in the common/policies.py file lines 146-151:

```
if recurrent_tensors is not None:
                    # recurrent architecture, need a few more steps
                    nenv = nbatch // nsteps
                    assert nenv > 0, 'Bad input for recurrent policy: batch size {} smaller than nsteps {}'.format(nbatch, nsteps)
                    policy_latent, recurrent_tensors = policy_network(encoded_x, nenv)
                    extra_tensors.update(recurrent_tensors)
```

And this only occurs for recurrent policies. If  these policies are not supported, perhaps the documentation should be updated, as in neither the readme or the learn function of the acer.py module is this mentioned.

**Comment by ethanwaldie** [comment]
I have added the required arguments, and it seems to allow the model to run.

**Comment by ethanwaldie** [comment]
However I am now getting warnings about early stopping of my environment.

**Comment by ethanwaldie** [comment]
Seeing as the PR has been merged. This can be closed.
