### ISSUE TITLE
error when i run python -m baselines.run --alg=ppo2 .... HELP please

### ISSUE THREAD

**Issue by sosinfo212** [openai/baselines#790]
hello  i have a problem i think in my python setup when i run 
python -m baselines.run --alg=ppo2 --env=Humanoid-v2 --network=mlp --num_timesteps=2e7
**i got this error** 
`Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/macos/mjpro150/baselines/baselines/run.py", line 9, in <module>
    from baselines.common.vec_env.vec_video_recorder import VecVideoRecorder
  File "baselines/common/__init__.py", line 3, in <module>
    from baselines.common.dataset import Dataset
  File "baselines/common/dataset.py", line 50
    def iterbatches(arrays, *, num_batches=None, batch_size=None, shuffle=True, include_final_partial_batch=True):
                             ^
SyntaxError: invalid syntax
`

**Comment by sosinfo212** [comment]
> You're using Python 2.7.
Yes

**Comment by DanielTakeshi** [comment]
@sosinfo212  You realize that is the problem, right?

**Comment by sosinfo212** [comment]
yes thank you

**Comment by pzhokhov** [comment]
Thanks @DanielTakeshi! That is correct, baselines are only compatible with python 3.5+. Closing this.
