### ISSUE TITLE
AttributeError: 'function' object has no attribute 'reset' inf rollout.py 

### ISSUE THREAD

**Issue by dovanhuong** [openai/baselines#798]
Dear all,
 I'm working with implement HER algorithm in UR5 environment. After I launch with the 1 epoches and reset my environment. It always tell to me 'function' object has no attribute 'reset'. The detail of my issue as below: 
2019-01-24 10:21:38.551305: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Creating a DDPG agent with action space 4 x [0.15       0.05       0.26179939 0.26179939]...
Traceback (most recent call last):
  File "/home/huong/catkin_ws/src/ur_gazebo_test2/experiment/train.py", line 224, in <module>
    main()
  File "/home/huong/env_tensorflow/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/huong/env_tensorflow/lib/python3.5/site-packages/click/core.py", line 717, in main
[INFO] [1548292899.141068, 877.931000]: DONE CONFIGURE DDPG
    rv = self.invoke(ctx)
  File "/home/huong/env_tensorflow/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/huong/env_tensorflow/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/huong/catkin_ws/src/ur_gazebo_test2/experiment/train.py", line 220, in main
    launch(**kwargs)
  File "/home/huong/catkin_ws/src/ur_gazebo_test2/experiment/train.py", line 194, in launch
    rollout_worker = RolloutWorker(params['make_env'], policy, dims, logger, **rollout_params)
  File "/home/huong/baselines/baselines/her/util.py", line 36, in wrapper
    return method(*positional_args, **keyword_args)
  File "/home/huong/baselines/baselines/her/rollout.py", line 42, in __init__
    self.reset_all_rollouts()
  File "/home/huong/baselines/baselines/her/rollout.py", line 46, in reset_all_rollouts
    self.obs_dict = self.venv.reset()
AttributeError: 'function' object has no attribute 'reset'

Process finished with exit code 1

My config.py and train.py as in  the link: https://github.com/dovanhuong/Baselines_UR5_issue
Has anyone can solve this issue or have suggestions, please tell to me know! I'm looking forward to hear your advices~

**Comment by pzhokhov** [comment]
Hi @dovanhuong ! From what I can see (had issues installing rospy; so cannot actually reproduce), there is a mismatch of version of baselines her that is partially copied into your train.py; and the current version of baselines her. Specifically, RolloutWorker *used to* take as an argument function that makes an environment; and now it takes an environment (more precisely, vectorized environment). 
I would recommend either installing baselines with older commit (146bbf886 or older would work); or re-writing train.py a little  - i.e. by adding 
```
from baselines.common.cmd_util import make_vec_env
env = make_vec_env(env, 'robotics', num_env=1, seed=None)
```
before initializing RolloutWorker

**Comment by dovanhuong** [comment]
hi @pzhokhov , you're right! Thank for your suggestion. I completed do downgrade version of  baselines and it's working fine so far! 

Thank and warm regards,
Huong Do Van

**Comment by SHYang1210** [comment]
Hi @dovanhuong ，I want to know how to lower the version of baselines，thank

**Comment by dovanhuong** [comment]
Could you please check the update version of baselines? I used the previous version before that time. Up to now I am no longer working with this. I'm so sorry for I don't remember the exact version! @SHYang1210

**Comment by rickstaa** [comment]
@pzhokhov Thanks for the solution above

**Comment by rickstaa** [comment]
@pzhokhov Thanks for the solutions you gave above. In my case, these solutions, however, do not solve the problem. I am currently trying to run a `train.py` script which is similar to the script from @dovanhuong (see [this repository for the exact code](https://github.com/rickstaa/my_fetch_training)). I, however, get the same error when doing so:

```
AttributeError: 'function' object has no attribute 'reset' inf rollout.py
```

I, therefore, tried both of the solutions you gave above:

**Revert back to the old version:**

I tried this but unfortunately, I run into the following error:

```
ModuleNotFoundError: No module named 'mujoco_py'
```

However, I would rather modify my train.py script such that I don't need to buy a mujoco license. Consequently, I, therefore, tried your second solution.

**Option 2: Initiate environment before  initializing RolloutWorker**

I tried adding the exact code given in the issue before the RolloutWorker:

```
from baselines.common.cmd_util import make_vec_env
env = make_vec_env(env, 'robotics', num_env=1, seed=None)
```

but when running the `train_modified.py` script I receive the following error:

```
Traceback (most recent call last):
  File "./src/my_fetch_train/scripts/train_modified.py", line 280, in <module>
    main()
  File "/home/ricks/.catkin_ws_python3/openai_venv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ricks/.catkin_ws_python3/openai_venv/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ricks/.catkin_ws_python3/openai_venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ricks/.catkin_ws_python3/openai_venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "./src/my_fetch_train/scripts/train_modified.py", line 276, in main
    launch(**kwargs)
  File "./src/my_fetch_train/scripts/train_modified.py", line 210, in launch
    env_vec, policy, dims, logger, **rollout_params
  File "/home/ricks/Development/robot_academy_ws/src/baselines/baselines/her/util.py", line 36, in wrapper
    return method(*positional_args, **keyword_args)
  File "/home/ricks/Development/robot_academy_ws/src/baselines/baselines/her/rollout.py", line 41, in __init__
    self.reset_all_rollouts()
  File "/home/ricks/Development/robot_academy_ws/src/baselines/baselines/her/rollout.py", line 46, in reset_all_rollouts
    self.initial_o = self.obs_dict['observation']
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

This appears to be caused since it uses the [DummyEnv](https://github.com/openai/baselines/blob/master/baselines/common/vec_env/dummy_vec_env.py) class instead of my own environment. I therefore tried the following code:

```
from baselines.common.cmd_util import make_robotics_env
env_vec= make_robotics_env(env, seed=rank_seed, rank=rank)
```

But this also gave me the error above. Lastly, I tried inputting a normal `gym.env` instead of a vectorized env by using the following code:

```
    rollout_worker = RolloutWorker(
        env_vec, policy, dims, logger, **rollout_params
    )
    rollout_worker.seed(rank_seed)
```

But I then received the following error:
```
Traceback (most recent call last):
  File "./src/my_fetch_train/scripts/train_modified.py", line 289, in <module>
    main()
  File "/home/ricks/.catkin_ws_python3/openai_venv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ricks/.catkin_ws_python3/openai_venv/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ricks/.catkin_ws_python3/openai_venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ricks/.catkin_ws_python3/openai_venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "./src/my_fetch_train/scripts/train_modified.py", line 285, in main
    launch(**kwargs)
  File "./src/my_fetch_train/scripts/train_modified.py", line 221, in launch
    rollout_worker.seed(rank_seed)
AttributeError: 'RolloutWorker' object has no attribute 'seed'
```

I was, therefore, wondering if somebody has an example on how to use the HER algorithm with the master branch of the [openai/baselines](https://github.com/openai/baselines/blob/master/baselines) repository?

**Comment by beerzzaaa** [comment]
i don't know how to play

ในวันที่ อ. 11 ก.พ. 2020 เวลา 01:03 Rick <notifications@github.com>
เขียนว่า:
