### ISSUE TITLE
I got an error when i run ppo and trpo....

### ISSUE THREAD

**Issue by wonchul-kim** [openai/baselines#80]
I typed ' python3 run_atari.py' to run it, and this error came up:
Traceback (most recent call last):
  File "run_atari.py", line 55, in <module>
    main()
  File "run_atari.py", line 52, in main
    train('PongNoFrameskip-v4', num_timesteps=40e6, seed=0, num_cpu=8)
  File "run_atari.py", line 26, in train
    logger.session().__enter__()
TypeError: __init__() missing 1 required positional argument: 'dir'
Traceback (most recent call last):
  File "run_atari.py", line 55, in <module>
    main()
  File "run_atari.py", line 52, in main
    train('PongNoFrameskip-v4', num_timesteps=40e6, seed=0, num_cpu=8)
  File "run_atari.py", line 26, in train
    logger.session().__enter__()
TypeError: __init__() missing 1 required positional argument: 'dir'

-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[51768,1],0]
  Exit code:    1
--------------------------------------------------------------------------
Traceback (most recent call last):
  File "run_atari.py", line 55, in <module>
    main()
  File "run_atari.py", line 52, in main
    train('PongNoFrameskip-v4', num_timesteps=40e6, seed=0, num_cpu=8)
  File "run_atari.py", line 21, in train
    whoami  = mpi_fork(num_cpu)
  File "/home/wonchul/Desktop/baselines-master/baselines/pposgd/mpi_fork.py", line 20, in mpi_fork
    subprocess.check_call(args, env=env)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mpirun', '-np', '8', '/usr/bin/python3', 'run_atari.py']' returned non-zero exit status 1

Do i have to add something with 'python3 run_atari.py' ?
Or is there any problem....?

Could you help me????

**Comment by JackieTseng** [comment]
@wonchul-kim Hi, have you solved this problem? How to fix it? THX

**Comment by wonchul-kim** [comment]
I just moved the all dependent files to the related folder

2017-08-02 19:09 GMT+09:00 Jackie Tseng <notifications@github.com>:
