### ISSUE TITLE
Baselines does not work for algorithmic env with mlp network

### ISSUE THREAD

**Issue by axeldomingues** [openai/baselines#810]
executed python -m baselines.run --alg=ppo2 --env=Copy-v0 --num_timesteps=35e6 --activation=tf.nn.selu --gamma=0.99 --num_env=8 --save_path=~/models/test_copy

got the following error: 
Training ppo2 on algorithmic:Copy-v0 with arguments
{'activation': <function selu at 0x0000000006D4F8C8>, 'gamma': 0.99, 'network': 'mlp'}
Traceback (most recent call last):
  File "C:\Users\adomingues\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\adomingues\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\adomingues\Desktop\ML\OpenAI\baselines\baselines\run.py", line 243, in <module>
    main(sys.argv)
  File "C:\Users\adomingues\Desktop\ML\OpenAI\baselines\baselines\run.py", line 210, in main
    model, env = train(args, extra_args)
  File "C:\Users\adomingues\Desktop\ML\OpenAI\baselines\baselines\run.py", line 84, in train
    **alg_kwargs
  File "C:\Users\adomingues\Desktop\ML\OpenAI\baselines\baselines\ppo2\ppo2.py", line 108, in learn
    max_grad_norm=max_grad_norm)
  File "C:\Users\adomingues\Desktop\ML\OpenAI\baselines\baselines\ppo2\model.py", line 34, in __init__
    act_model = policy(nbatch_act, 1, sess)
  File "C:\Users\adomingues\Desktop\ML\OpenAI\baselines\baselines\common\policies.py", line 175, in policy_fn
    **extra_tensors
  File "C:\Users\adomingues\Desktop\ML\OpenAI\baselines\baselines\common\policies.py", line 47, in __init__
    self.pdtype = make_pdtype(env.action_space)
  File "C:\Users\adomingues\Desktop\ML\OpenAI\baselines\baselines\common\distributions.py", line 289, in make_pdtype
    raise NotImplementedError
NotImplementedError

**Comment by pzhokhov** [comment]
Hi @axeldomingues! I confirm the issue; this happens because "Copy" environment has tuple action space that is not currently supported by baselines.

**Comment by pzhokhov** [comment]
On the high level what needs to be implemented is subclasses of PdType and Pd classes (in baselines/common/distributions.py) to describe probability distribution over the tuple space, and methods such as `mode`, `neglogp`, `kl`, `entropy`.  The simplest approach could be to assume independent probability distributions for each component of the tuple. This way all methods can be expressed through methods of distributions that correspond to sub-spaces. For instance, if your space is `Tuple(Discrete(5), Discrete(5))` then corresponding distribution (say, TuplePd) will wrap two CatergoricalPd's. Then `mode()` will return `(first.mode(),  second.mode())`, and `entropy()` will return `first.entropy() + second.entropy()`. 
Does that make sense?

**Comment by axeldomingues** [comment]
Hi @pzhokhov ,

Thanks for your reply. It makes sense. Will try to work this around and see.

Thank you!
