### ISSUE TITLE
IndexError: invalid index to scalar variable.

### ISSUE THREAD

**Issue by bmwant** [openai/baselines#839]
Hey, I'm trying to visualize model trained with 
```
python -m baselines.run --alg=deepq --env=PongNoFrameskip-v4 --num_timesteps=1e4 --save_path=~/models/pong_10K_deepq
```
by loading saved model like this
```
python -m baselines.run --alg=deepq --env=PongNoFrameskip-v4 --num_timesteps=0 --load_path=~/models/pong_10K_deepq --play
```

But instead of visualizing it throws an error
```
Logging to /var/folders/vy/mgpxtlld3q3cltdt357grl2c0000gn/T/openai-2019-02-28-22-25-59-032839
env_type: atari
Training deepq on atari:PongNoFrameskip-v4 with arguments
{'network': 'conv_only', 'lr': 0.0001, 'buffer_size': 10000, 'exploration_fraction': 0.1, 'exploration_final_eps': 0.01, 'train_freq': 4, 'learning_starts': 10000, 'target_network_update_freq': 1000, 'gamma': 0.99, 'prioritized_replay': True, 'prioritized_replay_alpha': 0.6, 'checkpoint_freq': 10000, 'checkpoint_path': None, 'dueling': True, 'load_path': '~/models/pong_1K_deepq'}
2019-02-28 22:25:59.679533: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
WARNING:tensorflow:From /Users/bmwant/pr/baselines/baselines/common/input.py:57: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From /Users/bmwant/.pyenv/versions/baselines/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /Users/bmwant/.pyenv/versions/baselines/lib/python3.7/site-packages/tensorflow/contrib/layers/python/layers/layers.py:1624: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
WARNING:tensorflow:From /Users/bmwant/.pyenv/versions/baselines/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Loaded model from ~/models/pong_1K_deepq
Running trained model
Traceback (most recent call last):
  File "/Users/bmwant/.pyenv/versions/3.7.2/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/bmwant/.pyenv/versions/3.7.2/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/bmwant/pr/baselines/baselines/run.py", line 244, in <module>
    main(sys.argv)
  File "/Users/bmwant/pr/baselines/baselines/run.py", line 231, in main
    episode_rew += rew[0]
IndexError: invalid index to scalar variable.
```
- `Python 3.7.2`
- `tensorflow==1.13.1`
- `-e git+git@github.com:openai/baselines.git@b875fb7b5e4feb85b9f1f1bf4e78f64c75595664#egg=baselines`
- `gym==0.12.0`

**Comment by tylerroost** [comment]
I second this seems to only occur with deepq. I tried same environment with ppo2 and it visualized after same number of steps

**Comment by Draichi** [comment]
I'm having the same issue as @bmwant  with deepq, is running ok with ppo2 though.

**Comment by pzhokhov** [comment]
This happens because deepq currently does not support vectorized environments... As a patch, I'd rather have a check like `isinstance(env, VecEnv)` - while it achieves the same purpose as comparing reward to typing.Sequence, this a) points more directly to the source of the problem and b) works with reward being, for instance, a 1-d numpy array (per my limited experiments, isinstance(rew, typing.Sequence does not). Fixed upstream, closing this
