### ISSUE TITLE
deepq is not working in the latest master branch

### ISSUE THREAD

**Issue by haochihlin** [openai/baselines#852]
Hi,
I cloned the latest master branch of baselines and tested deepq today,
but it shows errors with "print(f'episode_rew={episode_rew}')"

Command I used: `$ python -m baselines.run --alg=deepq --env=CartPole-v0`

Whole terminal output:
`$ python -m baselines.run --alg=deepq --env=CartPole-v0`

`Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 144, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/hlin/.virtualenvs/benchmarks/lib/python3.5/site-packages/baselines/run.py", line 235
    print(f'episode_rew={episode_rew}')
                                     ^
SyntaxError: invalid syntax
`

Since I don't meet this issue last week as I cloned the previous version of master branch,
So, I removed the line `print(f'episode_rew={episode_rew}')` in `run.py`, it works well now.

Maybe you can check and test it again.

**Comment by pzhokhov** [comment]
yeah, some f-strings leaked into that commit and broke python 3.5 compatibility. Sorry about that! Should be fixed now.
