### ISSUE TITLE
Training stops with: Self-adjoint eigen decomposition was not successful. The input might not be valid.

### ISSUE THREAD

**Issue by florath** [openai/baselines#909]
When using the command described in the top Readme but for Breakout and with acktr, the program terminates after the given time steps. No result file is written.

I'm using tensorflow-gpu 1.13.1 with cuda 10.0 and libcudnn7 7.5.1.10-1+cuda10.0.

````
$ python -m baselines.run --alg=acktr --env=BreakoutNoFrameskip-v0 --num_timesteps=2e7 --save_path=./models/breakout_20M_acktr
...
---------------------------------
| eplenmean          | 183      |
| eprewmean          | 1.35     |
| explained_variance | 0        |
| fps                | 603      |
| nupdates           | 1.67e+05 |
| policy_entropy     | 1.39     |
| policy_loss        | -0.0919  |
| total_timesteps    | 2e+07    |
| value_loss         | 0.0651   |
---------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/florath/devel/ML01/baselines/baselines/run.py", line 244, in <module>
    main(sys.argv)
  File "/home/florath/devel/ML01/baselines/baselines/run.py", line 210, in main
    model, env = train(args, extra_args)
  File "/home/florath/devel/ML01/baselines/baselines/run.py", line 80, in train
    **alg_kwargs
  File "/home/florath/devel/ML01/baselines/baselines/acktr/acktr.py", line 157, in learn
    coord.join(enqueue_threads)
  File "/home/florath/devel/ML01/vml/lib/python3.7/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/florath/devel/ML01/vml/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/florath/devel/ML01/vml/lib/python3.7/site-packages/tensorflow/python/training/queue_runner_impl.py", line 257, in _run
    enqueue_callable()
  File "/home/florath/devel/ML01/vml/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1267, in _single_tensor_run
    results = self._call_tf_sessionrun(None, {}, fetch_list, [], None)
  File "/home/florath/devel/ML01/vml/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Self-adjoint eigen decomposition was not successful. The input might not be valid.
	 [[{{node cond_1/SelfAdjointEigV2_9}}]]
	 [[{{node cond_1/fifo_queue_enqueue}}]]
Exception ignored in: <function SubprocVecEnv.__del__ at 0x7fa7dcbd0400>
Traceback (most recent call last):
  File "/home/florath/devel/ML01/baselines/baselines/common/vec_env/subproc_vec_env.py", line 107, in __del__
  File "/home/florath/devel/ML01/baselines/baselines/common/vec_env/vec_env.py", line 98, in close
  File "/home/florath/devel/ML01/baselines/baselines/common/vec_env/subproc_vec_env.py", line 91, in close_extras
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 206, in send
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 368, in _send
BrokenPipeError: [Errno 32] Broken pipe
````

**Comment by wyh416152228** [comment]
I got the same problem.

**Comment by jtromans** [comment]
Were you able to resolve this @wyh416152228  @florath

**Comment by jameschapman19** [comment]
If any of your batches are size 1 then this can result in a failure. Pick a batch size that doesn't have N%batch_size=1 and it might fix it :)
