### ISSUE TITLE
When use 'env.render()', the error:"dexError: list index out of range"

### ISSUE THREAD

**Issue by chenshiyuhit** [openai/baselines#939]
Hi, when running the code:
`python -m baselines.run --alg=ppo2 --env=Pendulum-v0 --num_timesteps=0 --load_path=~/models/Pend-v0 --play`
The error is as follows:
`Running trained model
2019-06-22 16:05:51.063036: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally
Traceback (most recent call last):
  File "/home/csy/anaconda3/envs/mujoco-gym/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/csy/anaconda3/envs/mujoco-gym/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/csy/drl/mujoco-gym/baselines/baselines/run.py", line 256, in <module>
    main(sys.argv)
  File "/home/csy/drl/mujoco-gym/baselines/baselines/run.py", line 244, in main
    env.render()
  File "/home/csy/drl/mujoco-gym/baselines/baselines/common/vec_env/dummy_vec_env.py", line 79, in render
    return self.envs[0].render(mode=mode)
  File "/home/csy/drl/mujoco-gym/gym/gym/core.py", line 230, in render
    return self.env.render(mode, **kwargs)
  File "/home/csy/drl/mujoco-gym/gym/gym/core.py", line 230, in render
    return self.env.render(mode, **kwargs)
  File "/home/csy/drl/mujoco-gym/gym/gym/core.py", line 230, in render
    return self.env.render(mode, **kwargs)
  File "/home/csy/drl/mujoco-gym/gym/gym/envs/classic_control/pendulum.py", line 61, in render
    from gym.envs.classic_control import rendering
  File "/home/csy/drl/mujoco-gym/gym/gym/envs/classic_control/rendering.py", line 27, in <module>
    from pyglet.gl import *
  File "/home/csy/anaconda3/envs/mujoco-gym/lib/python3.6/site-packages/pyglet/gl/__init__.py", line 239, in <module>
    import pyglet.window
  File "/home/csy/anaconda3/envs/mujoco-gym/lib/python3.6/site-packages/pyglet/window/__init__.py", line 1896, in <module>
    gl._create_shadow_window()
  File "/home/csy/anaconda3/envs/mujoco-gym/lib/python3.6/site-packages/pyglet/gl/__init__.py", line 208, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/home/csy/anaconda3/envs/mujoco-gym/lib/python3.6/site-packages/pyglet/window/xlib/__init__.py", line 166, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/csy/anaconda3/envs/mujoco-gym/lib/python3.6/site-packages/pyglet/window/__init__.py", line 512, in __init__
    config = screen.get_best_config(template_config)
  File "/home/csy/anaconda3/envs/mujoco-gym/lib/python3.6/site-packages/pyglet/canvas/base.py", line 159, in get_best_config
    configs = self.get_matching_configs(template)
  File "/home/csy/anaconda3/envs/mujoco-gym/lib/python3.6/site-packages/pyglet/canvas/xlib.py", line 182, in get_matching_configs
    configs = template.match(canvas)
  File "/home/csy/anaconda3/envs/mujoco-gym/lib/python3.6/site-packages/pyglet/gl/xlib.py", line 31, in match
    have_13 = info.have_version(1, 3)
  File "/home/csy/anaconda3/envs/mujoco-gym/lib/python3.6/site-packages/pyglet/gl/glx_info.py", line 87, in have_version
    client_version = self.get_client_version().split()[0]
IndexError: list index out of range`

But, when I remove the code by:
`#  env.render()`
it works, and has non error. Why? 
My environment:
Ubuntu 14.04
tensorflow 1.13.1
pyglet 1.3.2
Thanks.

**Comment by harrysprogramming** [comment]
I have this error too, did u manage to find a solution?

**Comment by jxfruit** [comment]
hi, this issue has been solved?

**Comment by sizhe-wang** [comment]
I met the same issue. Did you find the solution?
