### ISSUE TITLE
When I run multiple thread experiment, it showed up this error. Could anyone help to solve it?

### ISSUE THREAD

**Issue by YijiongLin** [openai/baselines#998]
Hello!
When I run this command: **mpirun -np 2 python -m baselines.run --num_env=1 --alg=her --enFetchPickAndPlace-v1 --num_timesteps=2.5e6 --n_cycles=1**
, it showed up all the traceback as above. Could anyone help me to solve this problem?  

The most wired thing is that I can run it in the first time, but when I terminate the experiment with "ctrl+c" in the terminal, it cannot be run anymore and always showed up this problem. 
 
 **I ran it in commit number:  2bca7901f51c88cdef3ca0666c6a87c454a4dbe8**

```
Training...
Traceback (most recent call last):
  File "/home/bourne/anaconda3/envs/mirror/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/bourne/anaconda3/envs/mirror/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/bourne/baselines/baselines/run.py", line 250, in <module>
    main(sys.argv)
  File "/home/bourne/baselines/baselines/run.py", line 216, in main
    model, env = train(args, extra_args)
  File "/home/bourne/baselines/baselines/run.py", line 80, in train
    **alg_kwargs
  File "/home/bourne/baselines/baselines/her/her.py", line 177, in learn
    policy_save_interval=policy_save_interval, demo_file=demo_file)
  File "/home/bourne/baselines/baselines/her/her.py", line 56, in train
    logger.record_tabular(key, mpi_average(val))
  File "/home/bourne/baselines/baselines/her/her.py", line 19, in mpi_average
    return mpi_moments(np.array(value))[0]
  File "/home/bourne/baselines/baselines/common/mpi_moments.py", line 22, in mpi_moments
    mean, count = mpi_mean(x, axis=axis, comm=comm, keepdims=True)
  File "/home/bourne/baselines/baselines/common/mpi_moments.py", line 16, in mpi_mean
    comm.Allreduce(localsum, globalsum, op=MPI.SUM)
  File "mpi4py/MPI/Comm.pyx", line 714, in mpi4py.MPI.Comm.Allreduce
**mpi4py.MPI.Exception: MPI_ERR_IN_STATUS: error code in status**

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

**Comment by YijiongLin** [comment]
Could anyone help?

**Comment by YijiongLin** [comment]
Also, when I run this command **mpirun -np 8 python -m baselines.run --num_env=2 --alg=her --env=FetchPickAndPlace-v1 --num_timesteps=2.5e6**, it seems some new error also showed up.

```
Training...
Traceback (most recent call last):
  File "/home/bourne/anaconda3/envs/mirror/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/bourne/anaconda3/envs/mirror/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/bourne/baselines/baselines/run.py", line 250, in <module>
    main(sys.argv)
  File "/home/bourne/baselines/baselines/run.py", line 216, in main
    model, env = train(args, extra_args)
  File "/home/bourne/baselines/baselines/run.py", line 80, in train
    **alg_kwargs
  File "/home/bourne/baselines/baselines/her/her.py", line 177, in learn
    policy_save_interval=policy_save_interval, demo_file=demo_file)
  File "/home/bourne/baselines/baselines/her/her.py", line 56, in train
    logger.record_tabular(key, mpi_average(val))
  File "/home/bourne/baselines/baselines/her/her.py", line 19, in mpi_average
    return mpi_moments(np.array(value))[0]
  File "/home/bourne/baselines/baselines/common/mpi_moments.py", line 22, in mpi_moments
    mean, count = mpi_mean(x, axis=axis, comm=comm, keepdims=True)
  File "/home/bourne/baselines/baselines/common/mpi_moments.py", line 16, in mpi_mean
    comm.Allreduce(localsum, globalsum, op=MPI.SUM)
  File "mpi4py/MPI/Comm.pyx", line 714, in mpi4py.MPI.Comm.Allreduce
mpi4py.MPI.Exception: MPI_ERR_IN_STATUS: error code in status

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

Traceback (most recent call last):
  File "/home/bourne/anaconda3/envs/mirror/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/bourne/anaconda3/envs/mirror/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/bourne/baselines/baselines/run.py", line 250, in <module>
    main(sys.argv)
  File "/home/bourne/baselines/baselines/run.py", line 216, in main
    model, env = train(args, extra_args)
  File "/home/bourne/baselines/baselines/run.py", line 80, in train
    **alg_kwargs
  File "/home/bourne/baselines/baselines/her/her.py", line 177, in learn
    policy_save_interval=policy_save_interval, demo_file=demo_file)
  File "/home/bourne/baselines/baselines/her/her.py", line 56, in train
    logger.record_tabular(key, mpi_average(val))
  File "/home/bourne/baselines/baselines/her/her.py", line 19, in mpi_average
    return mpi_moments(np.array(value))[0]
  File "/home/bourne/baselines/baselines/common/mpi_moments.py", line 22, in mpi_moments
    mean, count = mpi_mean(x, axis=axis, comm=comm, keepdims=True)
  File "/home/bourne/baselines/baselines/common/mpi_moments.py", line 16, in mpi_mean
    comm.Allreduce(localsum, globalsum, op=MPI.SUM)
  File "mpi4py/MPI/Comm.pyx", line 714, in mpi4py.MPI.Comm.Allreduce
mpi4py.MPI.Exception: MPI_ERR_IN_STATUS: error code in status

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

Traceback (most recent call last):
  File "/home/bourne/anaconda3/envs/mirror/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/bourne/anaconda3/envs/mirror/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/bourne/baselines/baselines/run.py", line 250, in <module>
    main(sys.argv)
  File "/home/bourne/baselines/baselines/run.py", line 216, in main
    model, env = train(args, extra_args)
  File "/home/bourne/baselines/baselines/run.py", line 80, in train
    **alg_kwargs
  File "/home/bourne/baselines/baselines/her/her.py", line 177, in learn
    policy_save_interval=policy_save_interval, demo_file=demo_file)
  File "/home/bourne/baselines/baselines/her/her.py", line 56, in train
    logger.record_tabular(key, mpi_average(val))
  File "/home/bourne/baselines/baselines/her/her.py", line 19, in mpi_average
    return mpi_moments(np.array(value))[0]
  File "/home/bourne/baselines/baselines/common/mpi_moments.py", line 22, in mpi_moments
    mean, count = mpi_mean(x, axis=axis, comm=comm, keepdims=True)
  File "/home/bourne/baselines/baselines/common/mpi_moments.py", line 16, in mpi_mean
    comm.Allreduce(localsum, globalsum, op=MPI.SUM)
  File "mpi4py/MPI/Comm.pyx", line 714, in mpi4py.MPI.Comm.Allreduce
mpi4py.MPI.Exception: MPI_ERR_IN_STATUS: error code in status

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

Exception ignored in: <bound method SubprocVecEnv.__del__ of <baselines.common.vec_env.subproc_vec_env.SubprocVecEnv object at 0x7fd836fe99b0>>
Traceback (most recent call last):
  File "/home/bourne/baselines/baselines/common/vec_env/subproc_vec_env.py", line 107, in __del__
    self.close()
  File "/home/bourne/baselines/baselines/common/vec_env/vec_env.py", line 98, in close
    self.close_extras()
  File "/home/bourne/baselines/baselines/common/vec_env/subproc_vec_env.py", line 91, in close_extras
    remote.send(('close', None))
  File "/home/bourne/anaconda3/envs/mirror/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/bourne/anaconda3/envs/mirror/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/home/bourne/anaconda3/envs/mirror/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <bound method SubprocVecEnv.__del__ of <baselines.common.vec_env.subproc_vec_env.SubprocVecEnv object at 0x7f9189016940>>
Traceback (most recent call last):
  File "/home/bourne/baselines/baselines/common/vec_env/subproc_vec_env.py", line 107, in __del__
    self.close()
  File "/home/bourne/baselines/baselines/common/vec_env/vec_env.py", line 98, in close
    self.close_extras()
  File "/home/bourne/baselines/baselines/common/vec_env/subproc_vec_env.py", line 91, in close_extras
    remote.send(('close', None))
  File "/home/bourne/anaconda3/envs/mirror/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/bourne/anaconda3/envs/mirror/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/home/bourne/anaconda3/envs/mirror/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <bound method SubprocVecEnv.__del__ of <baselines.common.vec_env.subproc_vec_env.SubprocVecEnv object at 0x7effa0f849b0>>
Traceback (most recent call last):
  File "/home/bourne/baselines/baselines/common/vec_env/subproc_vec_env.py", line 107, in __del__
    self.close()
  File "/home/bourne/baselines/baselines/common/vec_env/vec_env.py", line 98, in close
    self.close_extras()
  File "/home/bourne/baselines/baselines/common/vec_env/subproc_vec_env.py", line 91, in close_extras
    remote.send(('close', None))
  File "/home/bourne/anaconda3/envs/mirror/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/bourne/anaconda3/envs/mirror/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/home/bourne/anaconda3/envs/mirror/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by pzhokhov** [comment]
I think this should fixes it: https://github.com/openai/baselines/pull/1000
